import { QUESTIONS as GEOGRAPHY } from '../geography/bank';
import type { Difficulty, Question } from './types';
import { q } from './types';

const EASY_IDS = new Set([
  'cap-italy',
  'cap-france',
  'cap-spain',
  'cap-uk',
  'cap-germany',
  'cap-usa',
  'cap-japan',
  'cap-china',
  'cap-india',
  'cap-egypt',
  'cap-greece',
  'cont-brazil',
  'cont-egypt',
  'cont-china',
  'cont-france',
  'cont-canada',
  'cont-australia',
  'cont-count',
  'cont-smallest',
  'cont-largest',
  'cont-antarctica',
  'country-fuji',
  'country-pyramids',
  'country-kangaroo',
  'country-maple',
  'country-pizza',
  'ocean-atlantic',
  'ocean-pacific',
  'ocean-indian',
  'ocean-arctic',
  'ocean-count',
  'ocean-pacific-place',
  'flag-japan',
  'flag-canada',
  'flag-usa',
  'flag-uk',
  'flag-france',
  'land-eiffel',
  'land-statue-liberty',
  'land-colosseum',
  'land-great-wall',
  'land-big-ben',
  'land-sydney',
  'phys-island',
  'phys-peninsula',
  'phys-desert',
  'phys-volcano',
  'phys-equator-climate',
  'phys-poles',
  'phys-rainforest',
  'phys-compass-n',
  'world-equator',
  'world-north-pole',
]);

const LATE_IDS = new Set([
  'cap-south-africa',
  'cap-kenya',
  'cap-turkey',
  'cap-argentina',
  'cap-australia',
  'cap-canada',
  'land-petra',
  'land-sagrada',
  'land-machu',
  'river-volga',
  'river-yangtze',
  'river-danube',
  'mt-blanc',
  'mt-table',
  'eu-iberia',
  'eu-danube-city',
  'eu-prague',
  'eu-baltic',
  'world-suez',
  'world-panama',
  'world-greenland',
  'world-largest-pop',
  'world-largest-country',
  'phys-delta',
  'phys-hemisphere-brazil',
  'phys-lake',
  'phys-canyon',
]);

function inferTier(id: string, category: string): Difficulty {
  if (LATE_IDS.has(id)) return 'late';
  if (EASY_IDS.has(id) || category === 'Continents') return 'easy';
  return 'mid';
}

const EXTRAS: Question[] = [
  q('cap-nigeria', 'Capitals', 'What is the capital of Nigeria?', 'Abuja', ['Abuja', 'Lagos', 'Accra', 'Nairobi'], 'mid'),
  q('cap-thailand', 'Capitals', 'What is the capital of Thailand?', 'Bangkok', ['Bangkok', 'Phuket', 'Hanoi', 'Manila'], 'easy'),
  q('cap-peru', 'Capitals', 'What is the capital of Peru?', 'Lima', ['Lima', 'Cusco', 'Quito', 'Bogotá'], 'mid'),
  q('cap-chile', 'Capitals', 'What is the capital of Chile?', 'Santiago', ['Santiago', 'Lima', 'Valparaíso', 'Buenos Aires'], 'mid'),
  q('cap-finland', 'Capitals', 'What is the capital of Finland?', 'Helsinki', ['Helsinki', 'Oslo', 'Tallinn', 'Stockholm'], 'mid'),
  q('cap-new-zealand', 'Capitals', 'What is the capital of New Zealand?', 'Wellington', ['Wellington', 'Auckland', 'Christchurch', 'Sydney'], 'late'),
  q('cap-morocco', 'Capitals', 'What is the capital of Morocco?', 'Rabat', ['Rabat', 'Marrakesh', 'Casablanca', 'Tunis'], 'late'),
  q('cap-vietnam', 'Capitals', 'What is the capital of Vietnam?', 'Hanoi', ['Hanoi', 'Ho Chi Minh City', 'Bangkok', 'Phnom Penh'], 'mid'),
  q('neigh-usa-canada', 'Countries', 'Which country is directly north of the contiguous United States?', 'Canada', ['Canada', 'Mexico', 'Greenland', 'Russia'], 'easy'),
  q('neigh-usa-mexico', 'Countries', 'Which country is directly south of the United States?', 'Mexico', ['Mexico', 'Canada', 'Cuba', 'Brazil'], 'easy'),
  q('neigh-spain-france', 'Countries', 'Spain’s long northern land border is with which country?', 'France', ['France', 'Italy', 'Germany', 'Morocco'], 'mid'),
  q('neigh-egypt-sudan', 'Countries', 'Which country is directly south of Egypt?', 'Sudan', ['Sudan', 'Kenya', 'Libya', 'Saudi Arabia'], 'late'),
  q('neigh-china-india', 'Countries', 'China and India share a long border in which mountain region?', 'The Himalayas', ['The Himalayas', 'The Alps', 'The Andes', 'The Rockies'], 'mid'),
  q('river-nile-mouth', 'Rivers', 'The Nile River empties into which sea?', 'Mediterranean Sea', ['Mediterranean Sea', 'Red Sea', 'Black Sea', 'Arabian Sea'], 'mid'),
  q('river-congo', 'Rivers', 'The Congo River is in which continent?', 'Africa', ['Africa', 'South America', 'Asia', 'Australia'], 'mid'),
  q('mt-k2', 'Mountains', 'K2, the world’s second-highest mountain, is in which range?', 'Karakoram', ['Karakoram', 'Alps', 'Andes', 'Atlas'], 'late'),
  q('mt-aoraki', 'Mountains', 'Aoraki / Mount Cook is the highest mountain in which country?', 'New Zealand', ['New Zealand', 'Australia', 'Chile', 'Japan'], 'late'),
  q('world-sahara-size', 'World', 'The Sahara is the world’s largest…', 'Hot desert', ['Hot desert', 'Ocean', 'Rainforest', 'Ice sheet'], 'easy'),
  q('world-amazon-continent', 'World', 'The Amazon rainforest is mainly in which continent?', 'South America', ['South America', 'Africa', 'Asia', 'Australia'], 'easy'),
  q('world-gobi', 'World', 'The Gobi Desert is mainly in which two countries?', 'China and Mongolia', ['China and Mongolia', 'Egypt and Libya', 'USA and Mexico', 'India and Nepal'], 'late'),
  q('eu-pyrenees', 'Europe', 'The Pyrenees mountains form a border between Spain and which country?', 'France', ['France', 'Italy', 'Portugal', 'Germany'], 'mid'),
  q('eu-sicily', 'Europe', 'Sicily is a large island belonging to which country?', 'Italy', ['Italy', 'Greece', 'Spain', 'France'], 'easy'),
  q('flag-ireland', 'Flags', 'Which country’s flag is green, white and orange in vertical stripes?', 'Ireland', ['Ireland', 'Italy', 'India', 'Ivory Coast'], 'mid'),
  q('land-taj-city', 'Landmarks', 'The Taj Mahal is in which Indian city?', 'Agra', ['Agra', 'Mumbai', 'New Delhi', 'Jaipur'], 'late'),
  q('phys-isthmus', 'Physical', 'A narrow strip of land joining two larger lands is called an…', 'Isthmus', ['Isthmus', 'Archipelago', 'Plateau', 'Fjord'], 'late'),
  q('phys-archipelago', 'Physical', 'A group of islands is called an…', 'Archipelago', ['Archipelago', 'Peninsula', 'Atoll desert', 'Delta'], 'mid'),
  q('ocean-southern-name', 'Oceans', 'The Southern Ocean is also sometimes called the…', 'Antarctic Ocean', ['Antarctic Ocean', 'Arctic Ocean', 'Caspian Ocean', 'Red Ocean'], 'mid'),
];

export const CLASSIC_QUESTIONS: Question[] = [
  ...GEOGRAPHY.map((item) => ({
    ...item,
    tier: inferTier(item.id, item.category),
  })),
  ...EXTRAS,
];
