import { QUESTIONS as GEOGRAPHY } from '../geography/bank';
import type { Difficulty, Question } from './types';
import { q } from './types';

const EASY_IDS = new Set([
  'cap-italy',
  'cap-france',
  'cap-spain',
  'cap-uk',
  'cap-germany',
  'cap-usa',
  'cap-japan',
  'cap-china',
  'cap-india',
  'cap-egypt',
  'cap-greece',
  'cont-brazil',
  'cont-egypt',
  'cont-china',
  'cont-france',
  'cont-canada',
  'cont-australia',
  'cont-count',
  'cont-smallest',
  'cont-largest',
  'cont-antarctica',
  'country-fuji',
  'country-pyramids',
  'country-kangaroo',
  'country-maple',
  'country-pizza',
  'ocean-atlantic',
  'ocean-pacific',
  'ocean-indian',
  'ocean-arctic',
  'ocean-count',
  'ocean-pacific-place',
  'flag-japan',
  'flag-canada',
  'flag-usa',
  'flag-uk',
  'flag-france',
  'land-eiffel',
  'land-statue-liberty',
  'land-colosseum',
  'land-great-wall',
  'land-big-ben',
  'land-sydney',
  'phys-island',
  'phys-peninsula',
  'phys-desert',
  'phys-volcano',
  'phys-equator-climate',
  'phys-poles',
  'phys-rainforest',
  'phys-compass-n',
  'world-equator',
  'world-north-pole',
]);

const LATE_IDS = new Set([
  'cap-south-africa',
  'cap-kenya',
  'cap-turkey',
  'cap-argentina',
  'cap-australia',
  'cap-canada',
  'land-petra',
  'land-sagrada',
  'land-machu',
  'river-volga',
  'river-yangtze',
  'river-danube',
  'mt-blanc',
  'mt-table',
  'eu-iberia',
  'eu-danube-city',
  'eu-prague',
  'eu-baltic',
  'world-suez',
  'world-panama',
  'world-greenland',
  'world-largest-pop',
  'world-largest-country',
  'phys-delta',
  'phys-hemisphere-brazil',
  'phys-lake',
  'phys-canyon',
]);

function inferTier(id: string, category: string): Difficulty {
  if (LATE_IDS.has(id)) return 'late';
  if (EASY_IDS.has(id) || category === 'Continents') return 'easy';
  return 'mid';
}

const EXTRAS: Question[] = [
  q('cap-nigeria', 'Capitals', 'What is the capital of Nigeria?', 'Abuja', ['Abuja', 'Lagos', 'Accra', 'Nairobi'], 'mid'),
  q('cap-thailand', 'Capitals', 'What is the capital of Thailand?', 'Bangkok', ['Bangkok', 'Phuket', 'Hanoi', 'Manila'], 'easy'),
  q('cap-peru', 'Capitals', 'What is the capital of Peru?', 'Lima', ['Lima', 'Cusco', 'Quito', 'Bogotá'], 'mid'),
  q('cap-chile', 'Capitals', 'What is the capital of Chile?', 'Santiago', ['Santiago', 'Lima', 'Valparaíso', 'Buenos Aires'], 'mid'),
  q('cap-finland', 'Capitals', 'What is the capital of Finland?', 'Helsinki', ['Helsinki', 'Oslo', 'Tallinn', 'Stockholm'], 'mid'),
  q('cap-new-zealand', 'Capitals', 'What is the capital of New Zealand?', 'Wellington', ['Wellington', 'Auckland', 'Christchurch', 'Sydney'], 'late'),
  q('cap-morocco', 'Capitals', 'What is the capital of Morocco?', 'Rabat', ['Rabat', 'Marrakesh', 'Casablanca', 'Tunis'], 'late'),
  q('cap-vietnam', 'Capitals', 'What is the capital of Vietnam?', 'Hanoi', ['Hanoi', 'Ho Chi Minh City', 'Bangkok', 'Phnom Penh'], 'mid'),
  q('neigh-usa-canada', 'Countries', 'Which country is directly north of the contiguous United States?', 'Canada', ['Canada', 'Mexico', 'Greenland', 'Russia'], 'easy'),
  q('neigh-usa-mexico', 'Countries', 'Which country is directly south of the United States?', 'Mexico', ['Mexico', 'Canada', 'Cuba', 'Brazil'], 'easy'),
  q('neigh-spain-france', 'Countries', 'Spain’s long northern land border is with which country?', 'France', ['France', 'Italy', 'Germany', 'Morocco'], 'mid'),
  q('neigh-egypt-sudan', 'Countries', 'Which country is directly south of Egypt?', 'Sudan', ['Sudan', 'Kenya', 'Libya', 'Saudi Arabia'], 'late'),
  q('neigh-china-india', 'Countries', 'China and India share a long border in which mountain region?', 'The Himalayas', ['The Himalayas', 'The Alps', 'The Andes', 'The Rockies'], 'mid'),
  q('river-nile-mouth', 'Rivers', 'The Nile River empties into which sea?', 'Mediterranean Sea', ['Mediterranean Sea', 'Red Sea', 'Black Sea', 'Arabian Sea'], 'mid'),
  q('river-congo', 'Rivers', 'The Congo River is in which continent?', 'Africa', ['Africa', 'South America', 'Asia', 'Australia'], 'mid'),
  q('mt-k2', 'Mountains', 'K2, the world’s second-highest mountain, is in which range?', 'Karakoram', ['Karakoram', 'Alps', 'Andes', 'Atlas'], 'late'),
  q('mt-aoraki', 'Mountains', 'Aoraki / Mount Cook is the highest mountain in which country?', 'New Zealand', ['New Zealand', 'Australia', 'Chile', 'Japan'], 'late'),
  q('world-sahara-size', 'World', 'The Sahara is the world’s largest…', 'Hot desert', ['Hot desert', 'Ocean', 'Rainforest', 'Ice sheet'], 'easy'),
  q('world-amazon-continent', 'World', 'The Amazon rainforest is mainly in which continent?', 'South America', ['South America', 'Africa', 'Asia', 'Australia'], 'easy'),
  q('world-gobi', 'World', 'The Gobi Desert is mainly in which two countries?', 'China and Mongolia', ['China and Mongolia', 'Egypt and Libya', 'USA and Mexico', 'India and Nepal'], 'late'),
  q('eu-pyrenees', 'Europe', 'The Pyrenees mountains form a border between Spain and which country?', 'France', ['France', 'Italy', 'Portugal', 'Germany'], 'mid'),
  q('eu-sicily', 'Europe', 'Sicily is a large island belonging to which country?', 'Italy', ['Italy', 'Greece', 'Spain', 'France'], 'easy'),
  q('flag-ireland', 'Flags', 'Which country’s flag is green, white and orange in vertical stripes?', 'Ireland', ['Ireland', 'Italy', 'India', 'Ivory Coast'], 'mid'),
  q('land-taj-city', 'Landmarks', 'The Taj Mahal is in which Indian city?', 'Agra', ['Agra', 'Mumbai', 'New Delhi', 'Jaipur'], 'late'),
  q('phys-isthmus', 'Physical', 'A narrow strip of land joining two larger lands is called an…', 'Isthmus', ['Isthmus', 'Archipelago', 'Plateau', 'Fjord'], 'late'),
  q('phys-archipelago', 'Physical', 'A group of islands is called an…', 'Archipelago', ['Archipelago', 'Peninsula', 'Atoll desert', 'Delta'], 'mid'),
  q('ocean-southern-name', 'Oceans', 'The Southern Ocean is also sometimes called the…', 'Antarctic Ocean', ['Antarctic Ocean', 'Arctic Ocean', 'Caspian Ocean', 'Red Ocean'], 'mid'),
  q('cap-denmark', 'Capitals', 'What is the capital of Denmark?', 'Copenhagen', ['Copenhagen', 'Oslo', 'Stockholm', 'Amsterdam'], 'easy'),
  q('cap-hungary', 'Capitals', 'What is the capital of Hungary?', 'Budapest', ['Budapest', 'Vienna', 'Prague', 'Bucharest'], 'mid'),
  q('cap-czech', 'Capitals', 'What is the capital of Czechia (the Czech Republic)?', 'Prague', ['Prague', 'Vienna', 'Bratislava', 'Warsaw'], 'mid'),
  q('cap-austria', 'Capitals', 'What is the capital of Austria?', 'Vienna', ['Vienna', 'Salzburg', 'Munich', 'Zurich'], 'easy'),
  q('cap-switzerland', 'Capitals', 'What is the capital of Switzerland?', 'Bern', ['Bern', 'Zurich', 'Geneva', 'Vienna'], 'late'),
  q('cap-indonesia', 'Capitals', 'What is the capital of Indonesia?', 'Jakarta', ['Jakarta', 'Bali', 'Manila', 'Bangkok'], 'mid'),
  q('cap-philippines', 'Capitals', 'What is the capital of the Philippines?', 'Manila', ['Manila', 'Cebu', 'Jakarta', 'Hanoi'], 'mid'),
  q('cap-saudi', 'Capitals', 'What is the capital of Saudi Arabia?', 'Riyadh', ['Riyadh', 'Mecca', 'Dubai', 'Cairo'], 'late'),
  q('cap-uae', 'Capitals', 'What is the capital of the United Arab Emirates?', 'Abu Dhabi', ['Abu Dhabi', 'Dubai', 'Doha', 'Riyadh'], 'late'),
  q('cap-colombia', 'Capitals', 'What is the capital of Colombia?', 'Bogotá', ['Bogotá', 'Medellín', 'Lima', 'Caracas'], 'mid'),
  q('cap-cuba', 'Capitals', 'What is the capital of Cuba?', 'Havana', ['Havana', 'Miami', 'Kingston', 'San Juan'], 'easy'),
  q('cont-russia', 'Continents', 'Russia is mostly in which continent?', 'Asia', ['Asia', 'Europe', 'Africa', 'North America'], 'mid'),
  q('cont-iceland', 'Continents', 'Iceland is usually grouped with which continent?', 'Europe', ['Europe', 'North America', 'Asia', 'Africa'], 'mid'),
  q('neigh-portugal-spain', 'Countries', 'Portugal shares its only land border with which country?', 'Spain', ['Spain', 'France', 'Italy', 'Morocco'], 'easy'),
  q('neigh-germany-france', 'Countries', 'Germany’s long western land border is with which country?', 'France', ['France', 'Spain', 'Italy', 'Greece'], 'mid'),
  q('neigh-usa-alaska', 'Countries', 'The US state of Alaska has a land border with which country?', 'Canada', ['Canada', 'Russia', 'Mexico', 'Greenland'], 'mid'),
  q('neigh-brazil-argentina', 'Countries', 'Brazil has a long southern land border with which country?', 'Argentina', ['Argentina', 'Chile', 'Peru', 'Mexico'], 'late'),
  q('neigh-india-pakistan', 'Countries', 'India’s western neighbor is which country?', 'Pakistan', ['Pakistan', 'Thailand', 'Japan', 'Iran'], 'mid'),
  q('land-mount-rushmore', 'Landmarks', 'Mount Rushmore is in which country?', 'United States', ['United States', 'Canada', 'Australia', 'South Africa'], 'easy'),
  q('land-stonehenge', 'Landmarks', 'Stonehenge is a prehistoric stone circle in which country?', 'United Kingdom', ['United Kingdom', 'Ireland', 'France', 'Germany'], 'mid'),
  q('land-angkor', 'Landmarks', 'Angkor Wat is a famous temple complex in which country?', 'Cambodia', ['Cambodia', 'India', 'Thailand', 'Vietnam'], 'late'),
  q('land-moai', 'Landmarks', 'The giant stone heads called moai are on Easter Island, which belongs to…', 'Chile', ['Chile', 'Peru', 'New Zealand', 'Japan'], 'late'),
  q('river-amazon-ocean', 'Rivers', 'The Amazon River empties into which ocean?', 'Atlantic Ocean', ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'], 'mid'),
  q('river-ganges-sea', 'Rivers', 'The Ganges River flows mainly through India and into the…', 'Bay of Bengal', ['Bay of Bengal', 'Red Sea', 'Mediterranean Sea', 'Baltic Sea'], 'late'),
  q('mt-alps-continent', 'Mountains', 'The Alps are a major mountain range in which continent?', 'Europe', ['Europe', 'Asia', 'Africa', 'South America'], 'easy'),
  q('mt-andes-long', 'Mountains', 'Which is the longest mountain range on land?', 'The Andes', ['The Andes', 'The Alps', 'The Atlas', 'The Urals'], 'late'),
  q('ocean-atlantic-place', 'Oceans', 'The Atlantic Ocean lies between the Americas and which continents?', 'Europe and Africa', ['Europe and Africa', 'Asia and Australia', 'Antarctica only', 'India and China'], 'easy'),
  q('ocean-indian-place', 'Oceans', 'India’s southern coast faces which ocean?', 'Indian Ocean', ['Indian Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean'], 'easy'),
  q('sea-mediterranean', 'Oceans', 'Italy is a peninsula in which sea?', 'Mediterranean Sea', ['Mediterranean Sea', 'Baltic Sea', 'Caribbean Sea', 'Red Sea'], 'easy'),
  q('sea-black', 'Oceans', 'The Black Sea is north of which country?', 'Turkey', ['Turkey', 'Spain', 'India', 'Brazil'], 'late'),
  q('sea-north', 'Oceans', 'The North Sea lies between the United Kingdom and which country?', 'Norway', ['Norway', 'Spain', 'Italy', 'Greece'], 'mid'),
  q('desert-antarctica', 'World', 'The largest desert on Earth, by area, is…', 'Antarctica', ['Antarctica', 'The Sahara', 'The Gobi', 'The Kalahari'], 'late'),
  q('desert-kalahari', 'World', 'The Kalahari Desert is in which continent?', 'Africa', ['Africa', 'Australia', 'Asia', 'South America'], 'mid'),
  q('desert-atacama', 'World', 'The Atacama Desert is in which continent?', 'South America', ['South America', 'Africa', 'Australia', 'Asia'], 'late'),
  q('island-greenland-place', 'World', 'Greenland is closer to which continent?', 'North America', ['North America', 'Australia', 'Africa', 'South America'], 'mid'),
  q('island-new-zealand', 'World', 'New Zealand is a country of islands in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'easy'),
  q('island-japan', 'World', 'Japan is a country made of islands in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'easy'),
  q('world-prime-meridian', 'World', 'The Prime Meridian passes through which city?', 'Greenwich', ['Greenwich', 'New York', 'Cairo', 'Tokyo'], 'late'),
  q('world-international-date', 'World', 'The International Date Line runs mostly through which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'late'),
  q('phys-hemisphere-usa', 'Physical', 'The contiguous United States is in which hemisphere?', 'Northern Hemisphere', ['Northern Hemisphere', 'Southern Hemisphere', 'Only eastern', 'Only polar'], 'easy'),
  q('phys-hemisphere-australia', 'Physical', 'Australia is in which hemisphere?', 'Southern Hemisphere', ['Southern Hemisphere', 'Northern Hemisphere', 'Only Arctic', 'Only polar night'], 'easy'),
  q('phys-savanna', 'Physical', 'A grassy tropical plain with scattered trees is often called a…', 'Savanna', ['Savanna', 'Tundra', 'Ice cap', 'Coral reef'], 'mid'),
  q('phys-tundra', 'Physical', 'A cold, treeless plain near the Arctic is called…', 'Tundra', ['Tundra', 'Rainforest', 'Savanna', 'Delta'], 'mid'),
  q('phys-fjord', 'Physical', 'A deep, narrow sea inlet with steep sides, common in Norway, is a…', 'Fjord', ['Fjord', 'Delta', 'Atoll', 'Plateau'], 'late'),
  q('phys-plateau', 'Physical', 'A large, mostly flat area of high land is called a…', 'Plateau', ['Plateau', 'Peninsula', 'Isthmus', 'Reef'], 'mid'),
  q('phys-compass-e', 'Physical', 'If you face north, which direction is to your right?', 'East', ['East', 'West', 'South', 'Up'], 'easy'),
  q('eu-iberia-portugal', 'Europe', 'Portugal is on which peninsula?', 'Iberian Peninsula', ['Iberian Peninsula', 'Italian Peninsula', 'Balkan Peninsula', 'Yucatán Peninsula'], 'mid'),
  q('country-panda', 'Countries', 'Giant pandas are native to which country?', 'China', ['China', 'Japan', 'India', 'Russia'], 'easy'),
  q('country-pyramids-giza', 'Countries', 'The Great Pyramid of Giza is near which city?', 'Cairo', ['Cairo', 'Alexandria', 'Luxor', 'Khartoum'], 'mid'),
];

export const CLASSIC_QUESTIONS: Question[] = [
  ...GEOGRAPHY.map((item) => ({
    ...item,
    tier: inferTier(item.id, item.category),
  })),
  ...EXTRAS,
];
