import type { Question } from './types';
import { q } from './types';

/** Astronomy / space questions written for about a 10-year-old. */
export const NIGHT_QUESTIONS: Question[] = [
  q('sp-closest-sun', 'Space', 'Which planet is closest to the Sun?', 'Mercury', ['Mercury', 'Earth', 'Mars', 'Jupiter'], 'easy'),
  q('sp-red-planet', 'Space', 'Which planet is called the Red Planet?', 'Mars', ['Mars', 'Venus', 'Neptune', 'Saturn'], 'easy'),
  q('sp-rings', 'Space', 'Which planet is famous for its rings?', 'Saturn', ['Saturn', 'Earth', 'Mercury', 'Mars'], 'easy'),
  q('sp-galaxy', 'Space', 'What galaxy do we live in?', 'The Milky Way', ['The Milky Way', 'Andromeda only', 'The Sun Cluster', 'The Moon Belt'], 'easy'),
  q('sp-day-night', 'Space', 'What causes day and night on Earth?', 'Earth rotating', ['Earth rotating', 'The Moon turning off', 'Clouds covering the Sun', 'The Sun switching sides'], 'easy'),
  q('sp-satellite', 'Space', 'What is Earth’s natural satellite?', 'The Moon', ['The Moon', 'Mars', 'The Sun', 'A comet'], 'easy'),
  q('sp-star-sun', 'Space', 'The Sun is a…', 'Star', ['Star', 'Planet', 'Moon', 'Comet'], 'easy'),
  q('sp-planets-count', 'Space', 'How many planets are in our Solar System?', '8', ['8', '9', '7', '12'], 'easy'),
  q('sp-earth-third', 'Space', 'Earth is which planet from the Sun?', 'Third', ['Third', 'First', 'Fifth', 'Seventh'], 'easy'),
  q('sp-moon-light', 'Space', 'The Moon shines mainly because it…', 'Reflects sunlight', ['Reflects sunlight', 'Makes its own fire', 'Is a star', 'Glows like a lamp'], 'easy'),
  q('sp-astronaut', 'Space', 'A person who travels to space is called an…', 'Astronaut', ['Astronaut', 'Geologist', 'Pilot only', 'Sailor'], 'easy'),
  q('sp-meteor-name', 'Space', 'A “shooting star” is usually a…', 'Meteor', ['Meteor', 'Planet', 'Galaxy', 'Rainbow'], 'easy'),
  q('sp-comet', 'Space', 'A comet is a chunk of ice and dust that…', 'Orbits the Sun', ['Orbits the Sun', 'Sits on the Moon', 'Is a type of cloud', 'Is Earth’s twin'], 'easy'),
  q('sp-constellation', 'Space', 'A constellation is a…', 'Pattern of stars', ['Pattern of stars', 'Kind of planet', 'Type of moon rock', 'Solar flare'], 'easy'),
  q('sp-gravity-down', 'Space', 'Gravity on Earth pulls objects…', 'Toward the ground', ['Toward the ground', 'Into the sky', 'Only toward the Moon', 'Only toward Mars'], 'easy'),
  q('sp-telescope', 'Space', 'A telescope is used to…', 'See faraway objects', ['See faraway objects', 'Cook food', 'Measure rain', 'Dig soil'], 'easy'),
  q('sp-solar-system', 'Space', 'The Solar System is the Sun and everything that…', 'Orbits the Sun', ['Orbits the Sun', 'Orbits the Moon only', 'Lives in the ocean', 'Makes rainbows'], 'easy'),
  q('sp-biggest-planet', 'Space', 'Which is the largest planet in our Solar System?', 'Jupiter', ['Jupiter', 'Earth', 'Mars', 'Mercury'], 'easy'),
  q('sp-smallest-planet', 'Space', 'Which is the smallest planet in our Solar System?', 'Mercury', ['Mercury', 'Earth', 'Saturn', 'Neptune'], 'mid'),
  q('sp-venus-hot', 'Space', 'Which planet is the hottest in our Solar System?', 'Venus', ['Venus', 'Neptune', 'Uranus', 'Mars'], 'mid'),
  q('sp-blue-planet', 'Space', 'Earth is sometimes called the Blue Planet because of its…', 'Oceans', ['Oceans', 'Rings', 'Two suns', 'Purple sky'], 'easy'),
  q('sp-orbit-year', 'Space', 'Earth takes about one year to…', 'Orbit the Sun', ['Orbit the Sun', 'Spin once', 'Reach the Moon', 'Turn into a star'], 'easy'),
  q('sp-spin-day', 'Space', 'Earth takes about 24 hours to…', 'Spin once', ['Spin once', 'Orbit the Sun', 'Reach Mars', 'Make a comet'], 'easy'),
  q('sp-phases-moon', 'Space', 'The Moon’s changing shape in the sky is called its…', 'Phases', ['Phases', 'Seasons', 'Rings', 'Eclipses only'], 'mid'),
  q('sp-solar-eclipse', 'Space', 'A solar eclipse happens when the Moon blocks light from the…', 'Sun', ['Sun', 'Earth', 'Mars', 'Polaris'], 'mid'),
  q('sp-lunar-eclipse', 'Space', 'A lunar eclipse happens when Earth blocks sunlight from reaching the…', 'Moon', ['Moon', 'Sun', 'Jupiter', 'North Star'], 'mid'),
  q('sp-north-star', 'Space', 'Polaris is also called the…', 'North Star', ['North Star', 'Red Planet', 'Dog Star only', 'Sun Twin'], 'mid'),
  q('sp-ursa-major', 'Space', 'The Big Dipper is part of which constellation?', 'Ursa Major', ['Ursa Major', 'Orion’s Belt only', 'Saturn’s rings', 'The Milky Way hole'], 'mid'),
  q('sp-orion', 'Space', 'Orion is a constellation named after a…', 'Hunter', ['Hunter', 'River', 'Planet', 'Comet'], 'mid'),
  q('sp-first-moon', 'Space', 'The first people to walk on the Moon were from which country?', 'United States', ['United States', 'Brazil', 'Australia', 'Egypt'], 'mid'),
  q('sp-neil', 'Space', 'Who was the first person to walk on the Moon?', 'Neil Armstrong', ['Neil Armstrong', 'Albert Einstein', 'Isaac Newton', 'Galileo only'], 'mid'),
  q('sp-iss', 'Space', 'The ISS is a science lab that…', 'Orbits Earth', ['Orbits Earth', 'Sits on the Moon', 'Floats in the ocean', 'Is on Mars'], 'mid'),
  q('sp-asteroid', 'Space', 'An asteroid is a rocky object that mostly orbits…', 'The Sun', ['The Sun', 'Only the Moon', 'Only Earth cities', 'Inside volcanoes'], 'mid'),
  q('sp-meteorite', 'Space', 'A meteorite is space rock that has…', 'Landed on Earth', ['Landed on Earth', 'Become a star', 'Turned into a cloud', 'Become a planet'], 'mid'),
  q('sp-neptune-far', 'Space', 'Which planet is farthest from the Sun in our Solar System?', 'Neptune', ['Neptune', 'Mars', 'Venus', 'Earth'], 'mid'),
  q('sp-uranus-tilt', 'Space', 'Uranus is a giant planet that is…', 'Tilted on its side', ['Tilted on its side', 'Closest to the Sun', 'Earth’s moon', 'A star'], 'late'),
  q('sp-jupiter-moons', 'Space', 'Jupiter is known for having…', 'Many moons', ['Many moons', 'No gravity', 'People living there', 'Only one ring of fire'], 'mid'),
  q('sp-light-year', 'Space', 'A light-year measures…', 'Distance', ['Distance', 'Temperature', 'Weight', 'Time of day only'], 'late'),
  q('sp-black-hole', 'Space', 'A black hole has gravity so strong that…', 'Light cannot escape', ['Light cannot escape', 'It is a type of moon', 'It is Earth’s core', 'It makes rainbows'], 'late'),
  q('sp-andromeda', 'Space', 'Andromeda is a nearby…', 'Galaxy', ['Galaxy', 'Comet', 'Earth city', 'Kind of telescope'], 'late'),
  q('sp-seasons', 'Space', 'Earth’s seasons happen because Earth is…', 'Tilted as it orbits the Sun', ['Tilted as it orbits the Sun', 'Moving closer to Mars', 'Hollow', 'Always facing the Moon'], 'late'),
  q('sp-tides', 'Space', 'Ocean tides are caused mainly by the gravity of the…', 'Moon', ['Moon', 'Jupiter', 'Polaris', 'Asteroid belt'], 'late'),
  q('sp-atmosphere', 'Space', 'Earth’s atmosphere is a layer of…', 'Air', ['Air', 'Rock rings', 'Liquid metal', 'Moon dust'], 'easy'),
  q('sp-no-air-moon', 'Space', 'The Moon has almost no…', 'Air / atmosphere', ['Air / atmosphere', 'Rocks', 'Craters', 'Daytime'], 'mid'),
  q('sp-craters', 'Space', 'Round holes on the Moon were mostly made by…', 'Impacts', ['Impacts', 'Rain', 'Windstorms', 'Ocean waves'], 'mid'),
  q('sp-saturn-gas', 'Space', 'Saturn is a…', 'Gas giant', ['Gas giant', 'Dwarf moon', 'Kind of comet', 'Earth twin'], 'late'),
  q('sp-inner-planets', 'Space', 'The four planets closest to the Sun are mostly…', 'Rocky', ['Rocky', 'Made of rings only', 'Stars', 'Galaxies'], 'late'),
  q('sp-outer-planets', 'Space', 'Jupiter, Saturn, Uranus and Neptune are called…', 'Gas giants / giant planets', ['Gas giants / giant planets', 'Inner moons', 'Dwarf stars', 'Comet families'], 'late'),
  q('sp-pluto', 'Space', 'Pluto is now classed as a…', 'Dwarf planet', ['Dwarf planet', 'Star', 'Moon of Earth', 'Galaxy'], 'late'),
  q('sp-hubble', 'Space', 'The Hubble Space Telescope orbits…', 'Earth', ['Earth', 'The Sun’s core', 'Mars cities', 'The Moon’s ocean'], 'late'),
  q('sp-gravity-mass', 'Space', 'Gravity is stronger when an object has more…', 'Mass', ['Mass', 'Color', 'Sound', 'Clouds'], 'late'),
  q('sp-orbit-path', 'Space', 'An orbit is the path an object takes around…', 'Another object', ['Another object', 'A rainbow', 'A volcano', 'A desert'], 'mid'),
  q('sp-sun-center', 'Space', 'The centre of our Solar System is the…', 'Sun', ['Sun', 'Moon', 'Earth', 'Jupiter'], 'easy'),
  q('sp-mars-rovers', 'Space', 'Robots that explore the surface of Mars are often called…', 'Rovers', ['Rovers', 'Comets', 'Constellations', 'Eclipses'], 'mid'),
  q('sp-first-satellite', 'Space', 'Sputnik 1 was the first…', 'Artificial satellite', ['Artificial satellite', 'Person on the Moon', 'Planet discovered', 'Galaxy named'], 'late'),
  q('sp-milky-stars', 'Space', 'The Milky Way looks milky because it contains…', 'Billions of stars', ['Billions of stars', 'Only two planets', 'Earth’s oceans', 'Moon cheese'], 'mid'),
];
