import type { Question } from './types';
import { q } from './types';

export const TROPICAL_QUESTIONS: Question[] = [
  q('trop-equator', 'World', 'The Equator is an imaginary line around the…', 'Middle of the Earth', ['Middle of the Earth', 'North Pole', 'South Pole', 'Moon'], 'easy'),
  q('trop-climate', 'Climate', 'Places near the Equator are generally…', 'Warm', ['Warm', 'Frozen all year', 'Always deserts', 'Always snowy'], 'easy'),
  q('trop-rainforest', 'Climate', 'A dense, wet forest near the Equator is called a…', 'Rainforest', ['Rainforest', 'Tundra', 'Ice cap', 'Prairie'], 'easy'),
  q('trop-amazon-country', 'Countries', 'Most of the Amazon rainforest is in which country?', 'Brazil', ['Brazil', 'Mexico', 'Egypt', 'Spain'], 'easy'),
  q('trop-amazon-continent', 'Continents', 'The Amazon rainforest is in which continent?', 'South America', ['South America', 'Africa', 'Australia', 'Europe'], 'easy'),
  q('trop-caribbean-sea', 'Oceans', 'Cuba is an island in which sea?', 'Caribbean Sea', ['Caribbean Sea', 'Mediterranean Sea', 'Baltic Sea', 'Red Sea'], 'easy'),
  q('trop-hawaii-ocean', 'Oceans', 'The Hawaiian Islands are in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'easy'),
  q('trop-pacific-largest', 'Oceans', 'Which is the largest ocean on Earth?', 'Pacific', ['Pacific', 'Atlantic', 'Indian', 'Arctic'], 'easy'),
  q('trop-continents-count', 'Continents', 'How many continents are there on Earth?', '7', ['7', '5', '4', '9'], 'easy'),
  q('trop-africa-continent', 'Continents', 'Kenya is in which continent?', 'Africa', ['Africa', 'Asia', 'Europe', 'South America'], 'easy'),
  q('trop-india-continent', 'Continents', 'India is in which continent?', 'Asia', ['Asia', 'Africa', 'Europe', 'Australia'], 'easy'),
  q('trop-australia-both', 'Continents', 'Australia is both a country and a…', 'Continent', ['Continent', 'City', 'Ocean', 'Desert only'], 'easy'),
  q('trop-island-def', 'Physical', 'Land completely surrounded by water is called an…', 'Island', ['Island', 'Peninsula', 'Isthmus', 'Canyon'], 'easy'),
  q('trop-mango-asia', 'Food geography', 'Mangoes originally come from which region?', 'South Asia', ['South Asia', 'Antarctica', 'Northern Europe', 'The Arctic'], 'easy'),
  q('trop-banana-tropics', 'Food geography', 'Bananas grow best in which kind of climate?', 'Tropical', ['Tropical', 'Polar', 'High alpine snow', 'Always desert-dry'], 'easy'),
  q('trop-coconut-palm', 'Food geography', 'Coconuts grow on which kind of tree?', 'Palm tree', ['Palm tree', 'Pine tree', 'Oak tree', 'Maple tree'], 'easy'),
  q('trop-pineapple-amer', 'Food geography', 'Pineapples first grew in which region?', 'South America', ['South America', 'Antarctica', 'Northern Canada', 'Siberia'], 'easy'),
  q('trop-watermelon-warm', 'Food geography', 'Watermelons grow best in…', 'Warm weather', ['Warm weather', 'Permanent ice', 'Deep ocean', 'High Arctic tundra'], 'easy'),
  q('trop-pacific-islands', 'Regions', 'Fiji is a country made of islands in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], 'easy'),
  q('trop-madagascar', 'Countries', 'Madagascar is a large island country off which continent?', 'Africa', ['Africa', 'Europe', 'Australia', 'North America'], 'mid'),
  q('trop-indonesia', 'Countries', 'Indonesia is a large island country in which region?', 'Southeast Asia', ['Southeast Asia', 'Northern Europe', 'The Arctic', 'Southern Africa only'], 'mid'),
  q('trop-philippines', 'Countries', 'The Philippines is a country of many islands in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], 'mid'),
  q('trop-thailand', 'Countries', 'Thailand is in which region?', 'Southeast Asia', ['Southeast Asia', 'Eastern Europe', 'North Africa', 'Central America'], 'mid'),
  q('trop-vietnam', 'Countries', 'Vietnam is in which region?', 'Southeast Asia', ['Southeast Asia', 'South America', 'Northern Europe', 'The Caribbean'], 'mid'),
  q('trop-costa-rica', 'Countries', 'Costa Rica is in which region?', 'Central America', ['Central America', 'Eastern Europe', 'East Asia', 'North Africa'], 'mid'),
  q('trop-panama', 'Countries', 'Panama connects Central America to which continent?', 'South America', ['South America', 'Australia', 'Europe', 'Antarctica'], 'mid'),
  q('trop-colombia', 'Countries', 'Colombia is in which continent?', 'South America', ['South America', 'Africa', 'Europe', 'Australia'], 'mid'),
  q('trop-jamaica', 'Countries', 'Jamaica is an island in which sea?', 'Caribbean Sea', ['Caribbean Sea', 'Mediterranean Sea', 'North Sea', 'Caspian Sea'], 'mid'),
  q('trop-haiti', 'Countries', 'Haiti shares the island of Hispaniola with which country?', 'Dominican Republic', ['Dominican Republic', 'Cuba', 'Jamaica', 'Puerto Rico'], 'late'),
  q('trop-papua', 'Countries', 'Papua New Guinea is just north of which country?', 'Australia', ['Australia', 'India', 'Brazil', 'Egypt'], 'late'),
  q('trop-congo-forest', 'Regions', 'A huge tropical rainforest in Africa is the…', 'Congo rainforest', ['Congo rainforest', 'Gobi Desert', 'Alps forest', 'Siberian tundra'], 'mid'),
  q('trop-andes-tropic', 'Mountains', 'The Andes mountains run along which continent?', 'South America', ['South America', 'Africa', 'Europe', 'Australia'], 'mid'),
  q('trop-kilimanjaro', 'Mountains', 'Mount Kilimanjaro is in which continent?', 'Africa', ['Africa', 'Asia', 'South America', 'Europe'], 'mid'),
  q('trop-monsoon', 'Climate', 'A monsoon is a season of…', 'Heavy rain and wind', ['Heavy rain and wind', 'Only snow', 'No wind ever', 'Permanent night'], 'mid'),
  q('trop-humidity', 'Climate', 'Tropical rainforests are usually…', 'Hot and wet', ['Hot and wet', 'Cold and dry', 'Always frozen', 'Covered in ice sheets'], 'easy'),
  q('trop-coral', 'Physical', 'The Great Barrier Reef is off the coast of which country?', 'Australia', ['Australia', 'Brazil', 'Kenya', 'Spain'], 'mid'),
  q('trop-atoll', 'Physical', 'A ring-shaped coral island is often called an…', 'Atoll', ['Atoll', 'Fjord', 'Delta', 'Plateau'], 'late'),
  q('trop-amazon-river', 'Rivers', 'Which huge river flows through the Amazon rainforest?', 'Amazon', ['Amazon', 'Nile', 'Thames', 'Danube'], 'easy'),
  q('trop-nile-africa', 'Rivers', 'The Nile River is in which continent?', 'Africa', ['Africa', 'South America', 'Australia', 'Europe'], 'easy'),
  q('trop-mekong', 'Rivers', 'The Mekong River flows through several countries in…', 'Southeast Asia', ['Southeast Asia', 'Western Europe', 'North America', 'Southern Africa'], 'late'),
  q('trop-ganges', 'Rivers', 'The Ganges is a major river in which country?', 'India', ['India', 'Brazil', 'Egypt', 'Canada'], 'mid'),
  q('trop-equator-africa', 'World', 'The Equator passes through which of these continents?', 'Africa', ['Africa', 'Europe', 'Antarctica', 'North America'], 'mid'),
  q('trop-equator-sa', 'World', 'The Equator also passes through which of these continents?', 'South America', ['South America', 'Europe', 'Antarctica', 'Australia only'], 'mid'),
  q('trop-tropic-cancer', 'World', 'The Tropic of Cancer is in which hemisphere?', 'Northern Hemisphere', ['Northern Hemisphere', 'Southern Hemisphere', 'Only on the Moon', 'Only at the South Pole'], 'late'),
  q('trop-tropic-capricorn', 'World', 'The Tropic of Capricorn is in which hemisphere?', 'Southern Hemisphere', ['Southern Hemisphere', 'Northern Hemisphere', 'Only on Mars', 'Only at the North Pole'], 'late'),
  q('trop-seasons-eq', 'Climate', 'Near the Equator, day length through the year is…', 'About the same', ['About the same', 'Six months of night', 'Always polar night', 'Always 24-hour sun'], 'late'),
  q('trop-caribbean-region', 'Regions', 'The Caribbean is mainly a region of…', 'Islands and sea', ['Islands and sea', 'Ice caps', 'High Alps', 'Deserts of Mongolia'], 'easy'),
  q('trop-central-america', 'Regions', 'Central America lies between Mexico and which continent?', 'South America', ['South America', 'Europe', 'Australia', 'Antarctica'], 'mid'),
  q('trop-pacific-ring', 'Regions', 'Many Pacific islands sit in a region nicknamed the…', 'Ring of Fire', ['Ring of Fire', 'Ice Circle', 'Sahara Belt', 'Alps Arc'], 'late'),
  q('trop-sri-lanka', 'Countries', 'Sri Lanka is an island country near which larger country?', 'India', ['India', 'Brazil', 'Spain', 'Canada'], 'mid'),
  q('trop-maldives', 'Countries', 'The Maldives is a country of atolls in which ocean?', 'Indian Ocean', ['Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], 'late'),
  q('trop-seychelles', 'Countries', 'Seychelles is an island country in which ocean?', 'Indian Ocean', ['Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'Atlantic only'], 'late'),
  q('trop-fiji-region', 'Regions', 'Fiji is part of which island region?', 'Oceania / the South Pacific', ['Oceania / the South Pacific', 'The Mediterranean', 'The Caribbean only', 'The Baltic'], 'late'),
  q('trop-brazil-language', 'Countries', 'Brazil’s main language is…', 'Portuguese', ['Portuguese', 'Spanish', 'French', 'English'], 'mid'),
  q('trop-mexico-continent', 'Continents', 'Mexico is in which continent?', 'North America', ['North America', 'South America', 'Europe', 'Africa'], 'easy'),
  q('trop-kenya-safari', 'Countries', 'The Maasai Mara wildlife reserve is in which country?', 'Kenya', ['Kenya', 'Peru', 'Japan', 'Italy'], 'mid'),
  q('trop-galapagos', 'Landmarks', 'The Galápagos Islands belong to which country?', 'Ecuador', ['Ecuador', 'Australia', 'Spain', 'South Africa'], 'late'),
  q('trop-angel-falls', 'Landmarks', 'Angel Falls, a huge waterfall, is in which country?', 'Venezuela', ['Venezuela', 'Norway', 'Egypt', 'New Zealand'], 'late'),
  q('trop-borneo', 'Regions', 'Borneo is a large tropical island in which region?', 'Southeast Asia', ['Southeast Asia', 'The Caribbean', 'Northern Europe', 'East Africa only'], 'late'),
  q('trop-new-guinea', 'Regions', 'New Guinea is one of the world’s largest islands and lies north of…', 'Australia', ['Australia', 'Brazil', 'Greenland', 'Madagascar'], 'late'),
  q('trop-cuba-country', 'Countries', 'Cuba is an island country in which region?', 'The Caribbean', ['The Caribbean', 'The Mediterranean', 'Southeast Asia', 'The Arctic'], 'easy'),
  q('trop-bahamas', 'Countries', 'The Bahamas is a country of islands in which ocean?', 'Atlantic Ocean', ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'], 'easy'),
  q('trop-trinidad', 'Countries', 'Trinidad and Tobago is an island country near which continent?', 'South America', ['South America', 'Australia', 'Europe', 'Antarctica'], 'mid'),
  q('trop-belize', 'Countries', 'Belize is in which region?', 'Central America', ['Central America', 'Eastern Europe', 'East Africa', 'East Asia'], 'mid'),
  q('trop-honduras', 'Countries', 'Honduras is in which region?', 'Central America', ['Central America', 'Southern Africa', 'Northern Europe', 'Central Asia'], 'mid'),
  q('trop-nicaragua', 'Countries', 'Nicaragua is in which region?', 'Central America', ['Central America', 'Southeast Asia', 'The Balkans', 'The Arctic'], 'mid'),
  q('trop-guatemala', 'Countries', 'Guatemala is in which region?', 'Central America', ['Central America', 'East Asia', 'North Africa', 'Oceania'], 'mid'),
  q('trop-ecuador', 'Countries', 'Ecuador is named for the Equator and is in which continent?', 'South America', ['South America', 'Africa', 'Europe', 'Australia'], 'easy'),
  q('trop-peru-continent', 'Countries', 'Peru is in which continent?', 'South America', ['South America', 'Africa', 'Europe', 'Australia'], 'easy'),
  q('trop-venezuela', 'Countries', 'Venezuela is in which continent?', 'South America', ['South America', 'Africa', 'Asia', 'Europe'], 'easy'),
  q('trop-bolivia', 'Countries', 'Bolivia is a landlocked country in which continent?', 'South America', ['South America', 'Africa', 'Europe', 'Australia'], 'mid'),
  q('trop-paraguay', 'Countries', 'Paraguay is a landlocked country in which continent?', 'South America', ['South America', 'Asia', 'Europe', 'Africa'], 'late'),
  q('trop-ghana', 'Countries', 'Ghana is in which continent?', 'Africa', ['Africa', 'South America', 'Europe', 'Australia'], 'easy'),
  q('trop-nigeria-continent', 'Countries', 'Nigeria is in which continent?', 'Africa', ['Africa', 'Asia', 'South America', 'Europe'], 'easy'),
  q('trop-ethiopia', 'Countries', 'Ethiopia is in which continent?', 'Africa', ['Africa', 'Asia', 'Europe', 'South America'], 'easy'),
  q('trop-tanzania', 'Countries', 'Tanzania is in which continent?', 'Africa', ['Africa', 'Asia', 'South America', 'Europe'], 'easy'),
  q('trop-mozambique', 'Countries', 'Mozambique is on the southeast coast of which continent?', 'Africa', ['Africa', 'South America', 'Australia', 'Europe'], 'mid'),
  q('trop-cameroon', 'Countries', 'Cameroon is in which continent?', 'Africa', ['Africa', 'Asia', 'South America', 'Europe'], 'mid'),
  q('trop-malaysia', 'Countries', 'Malaysia is in which region?', 'Southeast Asia', ['Southeast Asia', 'Eastern Europe', 'Central America', 'North Africa'], 'mid'),
  q('trop-cambodia', 'Countries', 'Cambodia is in which region?', 'Southeast Asia', ['Southeast Asia', 'West Africa', 'The Caribbean', 'Northern Europe'], 'mid'),
  q('trop-laos', 'Countries', 'Laos is a landlocked country in which region?', 'Southeast Asia', ['Southeast Asia', 'Central America', 'The Balkans', 'East Africa'], 'late'),
  q('trop-myanmar', 'Countries', 'Myanmar (Burma) is in which region?', 'Southeast Asia', ['Southeast Asia', 'Southern Europe', 'The Caribbean', 'Central Africa'], 'late'),
  q('trop-singapore', 'Countries', 'Singapore is a small island country in which region?', 'Southeast Asia', ['Southeast Asia', 'The Caribbean', 'The Baltic', 'North Africa'], 'mid'),
  q('trop-taiwan', 'Countries', 'Taiwan is an island off the coast of which continent?', 'Asia', ['Asia', 'Africa', 'Europe', 'South America'], 'mid'),
  q('trop-samoa', 'Countries', 'Samoa is an island country in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'mid'),
  q('trop-tonga', 'Countries', 'Tonga is an island country in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'late'),
  q('trop-vanuatu', 'Countries', 'Vanuatu is an island country in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'late'),
  q('trop-mauritius', 'Countries', 'Mauritius is an island country in which ocean?', 'Indian Ocean', ['Indian Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean'], 'late'),
  q('trop-cap-kenya', 'Capitals', 'What is the capital of Kenya?', 'Nairobi', ['Nairobi', 'Lagos', 'Cairo', 'Cape Town'], 'mid'),
  q('trop-cap-brazil', 'Capitals', 'What is the capital of Brazil?', 'Brasília', ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Lisbon'], 'mid'),
  q('trop-cap-indonesia', 'Capitals', 'What is the capital of Indonesia?', 'Jakarta', ['Jakarta', 'Bali', 'Manila', 'Bangkok'], 'mid'),
  q('trop-cap-cuba', 'Capitals', 'What is the capital of Cuba?', 'Havana', ['Havana', 'Kingston', 'Miami', 'San Juan'], 'easy'),
  q('trop-cap-jamaica', 'Capitals', 'What is the capital of Jamaica?', 'Kingston', ['Kingston', 'Havana', 'Nassau', 'Port of Spain'], 'mid'),
  q('trop-cap-fiji', 'Capitals', 'What is the capital of Fiji?', 'Suva', ['Suva', 'Auckland', 'Honolulu', 'Sydney'], 'late'),
  q('trop-flag-jamaica', 'Flags', 'Which country’s flag is gold, green and black with a diagonal cross?', 'Jamaica', ['Jamaica', 'Brazil', 'South Africa', 'Ghana'], 'mid'),
  q('trop-flag-brazil', 'Flags', 'Which country’s flag is green with a yellow diamond and a blue globe?', 'Brazil', ['Brazil', 'Portugal', 'Mexico', 'Colombia'], 'easy'),
  q('trop-nile-longest', 'Rivers', 'Which is usually named as the world’s longest river?', 'Nile', ['Nile', 'Thames', 'Danube', 'Rhine'], 'easy'),
  q('trop-congo-ocean', 'Rivers', 'The Congo River empties into which ocean?', 'Atlantic Ocean', ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'], 'late'),
  q('trop-niger-river', 'Rivers', 'The Niger River is in which continent?', 'Africa', ['Africa', 'South America', 'Asia', 'Australia'], 'mid'),
  q('trop-orinoco', 'Rivers', 'The Orinoco River is in which continent?', 'South America', ['South America', 'Africa', 'Asia', 'Australia'], 'late'),
  q('trop-zambezi', 'Rivers', 'Victoria Falls is on which river?', 'Zambezi', ['Zambezi', 'Nile', 'Amazon', 'Danube'], 'late'),
  q('trop-victoria-falls', 'Landmarks', 'Victoria Falls is on the border of Zambia and which country?', 'Zimbabwe', ['Zimbabwe', 'Kenya', 'Egypt', 'Morocco'], 'late'),
  q('trop-table-mountain', 'Landmarks', 'Table Mountain overlooks which South African city?', 'Cape Town', ['Cape Town', 'Johannesburg', 'Nairobi', 'Lagos'], 'mid'),
  q('trop-uluru', 'Landmarks', 'Uluru (Ayers Rock) is a famous landmark in which country?', 'Australia', ['Australia', 'New Zealand', 'South Africa', 'Brazil'], 'mid'),
  q('trop-machu-picchu', 'Landmarks', 'Machu Picchu is an Incan citadel in which country?', 'Peru', ['Peru', 'Mexico', 'Spain', 'Egypt'], 'mid'),
  q('trop-chichen-itza', 'Landmarks', 'Chichén Itzá is a Maya pyramid site in which country?', 'Mexico', ['Mexico', 'Peru', 'Brazil', 'Spain'], 'mid'),
  q('trop-petronas', 'Landmarks', 'The Petronas Towers are in which country?', 'Malaysia', ['Malaysia', 'Japan', 'India', 'Australia'], 'late'),
  q('trop-sugarloaf', 'Landmarks', 'Sugarloaf Mountain is a landmark in which city?', 'Rio de Janeiro', ['Rio de Janeiro', 'Lisbon', 'Cape Town', 'Miami'], 'late'),
  q('trop-mt-kenya', 'Mountains', 'Mount Kenya is in which country?', 'Kenya', ['Kenya', 'Peru', 'India', 'Spain'], 'mid'),
  q('trop-andes-peru', 'Mountains', 'Machu Picchu sits in which mountain range?', 'The Andes', ['The Andes', 'The Alps', 'The Rockies', 'The Atlas'], 'mid'),
  q('trop-hawaii-volcano', 'Mountains', 'Mauna Loa is a huge volcano in which island group?', 'Hawaii', ['Hawaii', 'The Bahamas', 'The Canary Islands', 'Sicily'], 'mid'),
  q('trop-atlas-africa', 'Mountains', 'The Atlas Mountains are in which continent?', 'Africa', ['Africa', 'Europe', 'South America', 'Australia'], 'late'),
  q('trop-sahara-africa', 'World', 'The Sahara Desert is in which continent?', 'Africa', ['Africa', 'Asia', 'Australia', 'South America'], 'easy'),
  q('trop-namib', 'World', 'The Namib Desert is on the coast of which continent?', 'Africa', ['Africa', 'Australia', 'South America', 'Asia'], 'late'),
  q('trop-outback', 'World', 'Australia’s hot, dry inland region is often called the…', 'Outback', ['Outback', 'Pampas', 'Tundra', 'Fjords'], 'mid'),
  q('trop-amazon-basin', 'World', 'The huge lowland drained by the Amazon River is called the Amazon…', 'Basin', ['Basin', 'Plateau ice', 'Tundra', 'Fjord'], 'mid'),
  q('trop-gulf-mexico', 'Oceans', 'Cuba lies at the entrance to which gulf?', 'Gulf of Mexico', ['Gulf of Mexico', 'Persian Gulf', 'Gulf of Alaska', 'Gulf of Bothnia'], 'mid'),
  q('trop-red-sea', 'Oceans', 'The Red Sea lies between Africa and which peninsula?', 'Arabian Peninsula', ['Arabian Peninsula', 'Iberian Peninsula', 'Italian Peninsula', 'Yucatán Peninsula'], 'late'),
  q('trop-coral-sea', 'Oceans', 'The Coral Sea is off the northeast coast of which country?', 'Australia', ['Australia', 'Brazil', 'Kenya', 'Spain'], 'late'),
  q('trop-south-china-sea', 'Oceans', 'The Philippines, Vietnam and Malaysia all border which sea?', 'South China Sea', ['South China Sea', 'Baltic Sea', 'North Sea', 'Caribbean Sea'], 'late'),
  q('trop-trade-winds', 'Climate', 'Steady tropical winds once used by sailing ships are called…', 'Trade winds', ['Trade winds', 'Polar night winds', 'Ice gales', 'Desert silence'], 'late'),
  q('trop-wet-dry', 'Climate', 'Many tropical places have two main seasons. They are…', 'Wet and dry', ['Wet and dry', 'Winter and polar night', 'Only snow seasons', 'Always identical ice'], 'easy'),
  q('trop-hurricane-name', 'Climate', 'A strong tropical storm in the Atlantic is often called a…', 'Hurricane', ['Hurricane', 'Blizzard', 'Avalanche', 'Sandstorm only'], 'easy'),
  q('trop-typhoon-name', 'Climate', 'A strong tropical storm in the northwest Pacific is often called a…', 'Typhoon', ['Typhoon', 'Nor’easter', 'Chinook', 'Sirocco'], 'mid'),
  q('trop-cyclone-name', 'Climate', 'A strong tropical storm in the Indian Ocean is often called a…', 'Cyclone', ['Cyclone', 'Tornado alley', 'Ice storm', 'Haboob only'], 'mid'),
  q('trop-island-chain', 'Physical', 'A long chain of islands is sometimes called an…', 'Archipelago', ['Archipelago', 'Peninsula', 'Isthmus', 'Plateau'], 'mid'),
  q('trop-lagoon', 'Physical', 'A shallow pool of seawater separated from the ocean by a reef or sandbar is a…', 'Lagoon', ['Lagoon', 'Fjord', 'Glacier', 'Canyon'], 'mid'),
  q('trop-mangrove', 'Physical', 'Trees that grow in salty tropical coastal water are called…', 'Mangroves', ['Mangroves', 'Cacti', 'Pines', 'Oaks'], 'mid'),
  q('trop-volcano-island', 'Physical', 'Many Pacific islands were built by which process?', 'Volcanic eruptions', ['Volcanic eruptions', 'Glaciers only', 'River deltas only', 'Sandstorms'], 'easy'),
  q('trop-coral-polyps', 'Physical', 'Coral reefs are built mainly by tiny sea animals called…', 'Coral polyps', ['Coral polyps', 'Penguins', 'Cacti', 'Mosses'], 'late'),
  q('trop-equator-islands', 'World', 'Which of these countries does the Equator pass through?', 'Indonesia', ['Indonesia', 'Spain', 'Canada', 'New Zealand'], 'mid'),
  q('trop-neigh-brazil-peru', 'Countries', 'Brazil’s western Amazon neighbor includes which country?', 'Peru', ['Peru', 'Chile', 'Mexico', 'Egypt'], 'late'),
  q('trop-neigh-thailand-malaysia', 'Countries', 'Thailand’s southern land neighbor is which country?', 'Malaysia', ['Malaysia', 'Japan', 'India', 'Australia'], 'late'),
];
