import type { Question } from './types';
import { q } from './types';

export const TROPICAL_QUESTIONS: Question[] = [
  q('trop-equator', 'World', 'The Equator is an imaginary line around the…', 'Middle of the Earth', ['Middle of the Earth', 'North Pole', 'South Pole', 'Moon'], 'easy'),
  q('trop-climate', 'Climate', 'Places near the Equator are generally…', 'Warm', ['Warm', 'Frozen all year', 'Always deserts', 'Always snowy'], 'easy'),
  q('trop-rainforest', 'Climate', 'A dense, wet forest near the Equator is called a…', 'Rainforest', ['Rainforest', 'Tundra', 'Ice cap', 'Prairie'], 'easy'),
  q('trop-amazon-country', 'Countries', 'Most of the Amazon rainforest is in which country?', 'Brazil', ['Brazil', 'Mexico', 'Egypt', 'Spain'], 'easy'),
  q('trop-amazon-continent', 'Continents', 'The Amazon rainforest is in which continent?', 'South America', ['South America', 'Africa', 'Australia', 'Europe'], 'easy'),
  q('trop-caribbean-sea', 'Oceans', 'Cuba is an island in which sea?', 'Caribbean Sea', ['Caribbean Sea', 'Mediterranean Sea', 'Baltic Sea', 'Red Sea'], 'easy'),
  q('trop-hawaii-ocean', 'Oceans', 'The Hawaiian Islands are in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'easy'),
  q('trop-pacific-largest', 'Oceans', 'Which is the largest ocean on Earth?', 'Pacific', ['Pacific', 'Atlantic', 'Indian', 'Arctic'], 'easy'),
  q('trop-continents-count', 'Continents', 'How many continents are there on Earth?', '7', ['7', '5', '4', '9'], 'easy'),
  q('trop-africa-continent', 'Continents', 'Kenya is in which continent?', 'Africa', ['Africa', 'Asia', 'Europe', 'South America'], 'easy'),
  q('trop-india-continent', 'Continents', 'India is in which continent?', 'Asia', ['Asia', 'Africa', 'Europe', 'Australia'], 'easy'),
  q('trop-australia-both', 'Continents', 'Australia is both a country and a…', 'Continent', ['Continent', 'City', 'Ocean', 'Desert only'], 'easy'),
  q('trop-island-def', 'Physical', 'Land completely surrounded by water is called an…', 'Island', ['Island', 'Peninsula', 'Isthmus', 'Canyon'], 'easy'),
  q('trop-mango-asia', 'Food geography', 'Mangoes originally come from which region?', 'South Asia', ['South Asia', 'Antarctica', 'Northern Europe', 'The Arctic'], 'easy'),
  q('trop-banana-tropics', 'Food geography', 'Bananas grow best in which kind of climate?', 'Tropical', ['Tropical', 'Polar', 'High alpine snow', 'Always desert-dry'], 'easy'),
  q('trop-coconut-palm', 'Food geography', 'Coconuts grow on which kind of tree?', 'Palm tree', ['Palm tree', 'Pine tree', 'Oak tree', 'Maple tree'], 'easy'),
  q('trop-pineapple-amer', 'Food geography', 'Pineapples first grew in which region?', 'South America', ['South America', 'Antarctica', 'Northern Canada', 'Siberia'], 'easy'),
  q('trop-watermelon-warm', 'Food geography', 'Watermelons grow best in…', 'Warm weather', ['Warm weather', 'Permanent ice', 'Deep ocean', 'High Arctic tundra'], 'easy'),
  q('trop-pacific-islands', 'Regions', 'Fiji is a country made of islands in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], 'easy'),
  q('trop-madagascar', 'Countries', 'Madagascar is a large island country off which continent?', 'Africa', ['Africa', 'Europe', 'Australia', 'North America'], 'mid'),
  q('trop-indonesia', 'Countries', 'Indonesia is a large island country in which region?', 'Southeast Asia', ['Southeast Asia', 'Northern Europe', 'The Arctic', 'Southern Africa only'], 'mid'),
  q('trop-philippines', 'Countries', 'The Philippines is a country of many islands in which ocean?', 'Pacific Ocean', ['Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], 'mid'),
  q('trop-thailand', 'Countries', 'Thailand is in which region?', 'Southeast Asia', ['Southeast Asia', 'Eastern Europe', 'North Africa', 'Central America'], 'mid'),
  q('trop-vietnam', 'Countries', 'Vietnam is in which region?', 'Southeast Asia', ['Southeast Asia', 'South America', 'Northern Europe', 'The Caribbean'], 'mid'),
  q('trop-costa-rica', 'Countries', 'Costa Rica is in which region?', 'Central America', ['Central America', 'Eastern Europe', 'East Asia', 'North Africa'], 'mid'),
  q('trop-panama', 'Countries', 'Panama connects Central America to which continent?', 'South America', ['South America', 'Australia', 'Europe', 'Antarctica'], 'mid'),
  q('trop-colombia', 'Countries', 'Colombia is in which continent?', 'South America', ['South America', 'Africa', 'Europe', 'Australia'], 'mid'),
  q('trop-jamaica', 'Countries', 'Jamaica is an island in which sea?', 'Caribbean Sea', ['Caribbean Sea', 'Mediterranean Sea', 'North Sea', 'Caspian Sea'], 'mid'),
  q('trop-haiti', 'Countries', 'Haiti shares the island of Hispaniola with which country?', 'Dominican Republic', ['Dominican Republic', 'Cuba', 'Jamaica', 'Puerto Rico'], 'late'),
  q('trop-papua', 'Countries', 'Papua New Guinea is just north of which country?', 'Australia', ['Australia', 'India', 'Brazil', 'Egypt'], 'late'),
  q('trop-congo-forest', 'Regions', 'A huge tropical rainforest in Africa is the…', 'Congo rainforest', ['Congo rainforest', 'Gobi Desert', 'Alps forest', 'Siberian tundra'], 'mid'),
  q('trop-andes-tropic', 'Mountains', 'The Andes mountains run along which continent?', 'South America', ['South America', 'Africa', 'Europe', 'Australia'], 'mid'),
  q('trop-kilimanjaro', 'Mountains', 'Mount Kilimanjaro is in which continent?', 'Africa', ['Africa', 'Asia', 'South America', 'Europe'], 'mid'),
  q('trop-monsoon', 'Climate', 'A monsoon is a season of…', 'Heavy rain and wind', ['Heavy rain and wind', 'Only snow', 'No wind ever', 'Permanent night'], 'mid'),
  q('trop-humidity', 'Climate', 'Tropical rainforests are usually…', 'Hot and wet', ['Hot and wet', 'Cold and dry', 'Always frozen', 'Covered in ice sheets'], 'easy'),
  q('trop-coral', 'Physical', 'The Great Barrier Reef is off the coast of which country?', 'Australia', ['Australia', 'Brazil', 'Kenya', 'Spain'], 'mid'),
  q('trop-atoll', 'Physical', 'A ring-shaped coral island is often called an…', 'Atoll', ['Atoll', 'Fjord', 'Delta', 'Plateau'], 'late'),
  q('trop-amazon-river', 'Rivers', 'Which huge river flows through the Amazon rainforest?', 'Amazon', ['Amazon', 'Nile', 'Thames', 'Danube'], 'easy'),
  q('trop-nile-africa', 'Rivers', 'The Nile River is in which continent?', 'Africa', ['Africa', 'South America', 'Australia', 'Europe'], 'easy'),
  q('trop-mekong', 'Rivers', 'The Mekong River flows through several countries in…', 'Southeast Asia', ['Southeast Asia', 'Western Europe', 'North America', 'Southern Africa'], 'late'),
  q('trop-ganges', 'Rivers', 'The Ganges is a major river in which country?', 'India', ['India', 'Brazil', 'Egypt', 'Canada'], 'mid'),
  q('trop-equator-africa', 'World', 'The Equator passes through which of these continents?', 'Africa', ['Africa', 'Europe', 'Antarctica', 'North America'], 'mid'),
  q('trop-equator-sa', 'World', 'The Equator also passes through which of these continents?', 'South America', ['South America', 'Europe', 'Antarctica', 'Australia only'], 'mid'),
  q('trop-tropic-cancer', 'World', 'The Tropic of Cancer is in which hemisphere?', 'Northern Hemisphere', ['Northern Hemisphere', 'Southern Hemisphere', 'Only on the Moon', 'Only at the South Pole'], 'late'),
  q('trop-tropic-capricorn', 'World', 'The Tropic of Capricorn is in which hemisphere?', 'Southern Hemisphere', ['Southern Hemisphere', 'Northern Hemisphere', 'Only on Mars', 'Only at the North Pole'], 'late'),
  q('trop-seasons-eq', 'Climate', 'Near the Equator, day length through the year is…', 'About the same', ['About the same', 'Six months of night', 'Always polar night', 'Always 24-hour sun'], 'late'),
  q('trop-caribbean-region', 'Regions', 'The Caribbean is mainly a region of…', 'Islands and sea', ['Islands and sea', 'Ice caps', 'High Alps', 'Deserts of Mongolia'], 'easy'),
  q('trop-central-america', 'Regions', 'Central America lies between Mexico and which continent?', 'South America', ['South America', 'Europe', 'Australia', 'Antarctica'], 'mid'),
  q('trop-pacific-ring', 'Regions', 'Many Pacific islands sit in a region nicknamed the…', 'Ring of Fire', ['Ring of Fire', 'Ice Circle', 'Sahara Belt', 'Alps Arc'], 'late'),
  q('trop-sri-lanka', 'Countries', 'Sri Lanka is an island country near which larger country?', 'India', ['India', 'Brazil', 'Spain', 'Canada'], 'mid'),
  q('trop-maldives', 'Countries', 'The Maldives is a country of atolls in which ocean?', 'Indian Ocean', ['Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], 'late'),
  q('trop-seychelles', 'Countries', 'Seychelles is an island country in which ocean?', 'Indian Ocean', ['Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'Atlantic only'], 'late'),
  q('trop-fiji-region', 'Regions', 'Fiji is part of which island region?', 'Oceania / the South Pacific', ['Oceania / the South Pacific', 'The Mediterranean', 'The Caribbean only', 'The Baltic'], 'late'),
  q('trop-brazil-language', 'Countries', 'Brazil’s main language is…', 'Portuguese', ['Portuguese', 'Spanish', 'French', 'English'], 'mid'),
  q('trop-mexico-continent', 'Continents', 'Mexico is in which continent?', 'North America', ['North America', 'South America', 'Europe', 'Africa'], 'easy'),
  q('trop-kenya-safari', 'Countries', 'The Maasai Mara wildlife reserve is in which country?', 'Kenya', ['Kenya', 'Peru', 'Japan', 'Italy'], 'mid'),
  q('trop-galapagos', 'Landmarks', 'The Galápagos Islands belong to which country?', 'Ecuador', ['Ecuador', 'Australia', 'Spain', 'South Africa'], 'late'),
  q('trop-angel-falls', 'Landmarks', 'Angel Falls, a huge waterfall, is in which country?', 'Venezuela', ['Venezuela', 'Norway', 'Egypt', 'New Zealand'], 'late'),
  q('trop-borneo', 'Regions', 'Borneo is a large tropical island in which region?', 'Southeast Asia', ['Southeast Asia', 'The Caribbean', 'Northern Europe', 'East Africa only'], 'late'),
  q('trop-new-guinea', 'Regions', 'New Guinea is one of the world’s largest islands and lies north of…', 'Australia', ['Australia', 'Brazil', 'Greenland', 'Madagascar'], 'late'),
];
