export interface Question {
  id: string;
  category: string;
  prompt: string;
  correct: string;
  choices: [string, string, string, string];
  fact?: string;
}

export const QUESTIONS: Question[] = [
  // Capitals
  {
    id: 'cap-italy',
    category: 'Capitals',
    prompt: 'What is the capital of Italy?',
    correct: 'Rome',
    choices: ['Rome', 'Madrid', 'Athens', 'Lisbon'],
    fact: 'Rome has been an important city for more than 2,000 years.',
  },
  {
    id: 'cap-france',
    category: 'Capitals',
    prompt: 'What is the capital of France?',
    correct: 'Paris',
    choices: ['Paris', 'Lyon', 'Brussels', 'Geneva'],
  },
  {
    id: 'cap-spain',
    category: 'Capitals',
    prompt: 'What is the capital of Spain?',
    correct: 'Madrid',
    choices: ['Madrid', 'Barcelona', 'Seville', 'Lisbon'],
  },
  {
    id: 'cap-uk',
    category: 'Capitals',
    prompt: 'What is the capital of the United Kingdom?',
    correct: 'London',
    choices: ['London', 'Manchester', 'Edinburgh', 'Dublin'],
  },
  {
    id: 'cap-germany',
    category: 'Capitals',
    prompt: 'What is the capital of Germany?',
    correct: 'Berlin',
    choices: ['Berlin', 'Munich', 'Frankfurt', 'Vienna'],
  },
  {
    id: 'cap-usa',
    category: 'Capitals',
    prompt: 'What is the capital of the United States?',
    correct: 'Washington, D.C.',
    choices: ['Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'],
    fact: 'New York is the largest city, but not the capital.',
  },
  {
    id: 'cap-canada',
    category: 'Capitals',
    prompt: 'What is the capital of Canada?',
    correct: 'Ottawa',
    choices: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
  },
  {
    id: 'cap-japan',
    category: 'Capitals',
    prompt: 'What is the capital of Japan?',
    correct: 'Tokyo',
    choices: ['Tokyo', 'Kyoto', 'Osaka', 'Seoul'],
  },
  {
    id: 'cap-china',
    category: 'Capitals',
    prompt: 'What is the capital of China?',
    correct: 'Beijing',
    choices: ['Beijing', 'Shanghai', 'Hong Kong', 'Taipei'],
  },
  {
    id: 'cap-india',
    category: 'Capitals',
    prompt: 'What is the capital of India?',
    correct: 'New Delhi',
    choices: ['New Delhi', 'Mumbai', 'Kolkata', 'Bangalore'],
  },
  {
    id: 'cap-australia',
    category: 'Capitals',
    prompt: 'What is the capital of Australia?',
    correct: 'Canberra',
    choices: ['Canberra', 'Sydney', 'Melbourne', 'Perth'],
    fact: 'Sydney is famous, but Canberra is the capital.',
  },
  {
    id: 'cap-brazil',
    category: 'Capitals',
    prompt: 'What is the capital of Brazil?',
    correct: 'Brasília',
    choices: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Lisbon'],
  },
  {
    id: 'cap-mexico',
    category: 'Capitals',
    prompt: 'What is the capital of Mexico?',
    correct: 'Mexico City',
    choices: ['Mexico City', 'Cancún', 'Guadalajara', 'Monterrey'],
  },
  {
    id: 'cap-egypt',
    category: 'Capitals',
    prompt: 'What is the capital of Egypt?',
    correct: 'Cairo',
    choices: ['Cairo', 'Alexandria', 'Giza', 'Luxor'],
  },
  {
    id: 'cap-kenya',
    category: 'Capitals',
    prompt: 'What is the capital of Kenya?',
    correct: 'Nairobi',
    choices: ['Nairobi', 'Mombasa', 'Lagos', 'Addis Ababa'],
  },
  {
    id: 'cap-south-africa',
    category: 'Capitals',
    prompt: 'Which city is one of South Africa’s capitals and home to its parliament?',
    correct: 'Cape Town',
    choices: ['Cape Town', 'Johannesburg', 'Durban', 'Pretoria'],
    fact: 'South Africa has three capital cities for different parts of government.',
  },
  {
    id: 'cap-greece',
    category: 'Capitals',
    prompt: 'What is the capital of Greece?',
    correct: 'Athens',
    choices: ['Athens', 'Rome', 'Istanbul', 'Nicosia'],
  },
  {
    id: 'cap-portugal',
    category: 'Capitals',
    prompt: 'What is the capital of Portugal?',
    correct: 'Lisbon',
    choices: ['Lisbon', 'Porto', 'Madrid', 'Barcelona'],
  },
  {
    id: 'cap-sweden',
    category: 'Capitals',
    prompt: 'What is the capital of Sweden?',
    correct: 'Stockholm',
    choices: ['Stockholm', 'Oslo', 'Copenhagen', 'Helsinki'],
  },
  {
    id: 'cap-norway',
    category: 'Capitals',
    prompt: 'What is the capital of Norway?',
    correct: 'Oslo',
    choices: ['Oslo', 'Stockholm', 'Bergen', 'Copenhagen'],
  },
  {
    id: 'cap-ireland',
    category: 'Capitals',
    prompt: 'What is the capital of Ireland?',
    correct: 'Dublin',
    choices: ['Dublin', 'Belfast', 'Cork', 'Galway'],
  },
  {
    id: 'cap-poland',
    category: 'Capitals',
    prompt: 'What is the capital of Poland?',
    correct: 'Warsaw',
    choices: ['Warsaw', 'Kraków', 'Prague', 'Budapest'],
  },
  {
    id: 'cap-turkey',
    category: 'Capitals',
    prompt: 'What is the capital of Turkey?',
    correct: 'Ankara',
    choices: ['Ankara', 'Istanbul', 'Izmir', 'Athens'],
  },
  {
    id: 'cap-argentina',
    category: 'Capitals',
    prompt: 'What is the capital of Argentina?',
    correct: 'Buenos Aires',
    choices: ['Buenos Aires', 'Santiago', 'Lima', 'Montevideo'],
  },
  {
    id: 'cap-south-korea',
    category: 'Capitals',
    prompt: 'What is the capital of South Korea?',
    correct: 'Seoul',
    choices: ['Seoul', 'Busan', 'Tokyo', 'Beijing'],
  },

  // Continents & countries
  {
    id: 'cont-brazil',
    category: 'Continents',
    prompt: 'Which continent is Brazil in?',
    correct: 'South America',
    choices: ['South America', 'Europe', 'Asia', 'Africa'],
  },
  {
    id: 'cont-egypt',
    category: 'Continents',
    prompt: 'Which continent is Egypt mostly in?',
    correct: 'Africa',
    choices: ['Africa', 'Asia', 'Europe', 'Australia'],
  },
  {
    id: 'cont-china',
    category: 'Continents',
    prompt: 'Which continent is China in?',
    correct: 'Asia',
    choices: ['Asia', 'Europe', 'Africa', 'South America'],
  },
  {
    id: 'cont-france',
    category: 'Continents',
    prompt: 'Which continent is France in?',
    correct: 'Europe',
    choices: ['Europe', 'Asia', 'Africa', 'North America'],
  },
  {
    id: 'cont-canada',
    category: 'Continents',
    prompt: 'Which continent is Canada in?',
    correct: 'North America',
    choices: ['North America', 'Europe', 'Asia', 'South America'],
  },
  {
    id: 'cont-australia',
    category: 'Continents',
    prompt: 'Australia is both a country and a…',
    correct: 'Continent',
    choices: ['Continent', 'City', 'Ocean', 'Mountain'],
  },
  {
    id: 'cont-count',
    category: 'Continents',
    prompt: 'How many continents are there on Earth?',
    correct: '7',
    choices: ['7', '5', '6', '8'],
  },
  {
    id: 'cont-smallest',
    category: 'Continents',
    prompt: 'Which is the smallest continent?',
    correct: 'Australia',
    choices: ['Australia', 'Europe', 'Antarctica', 'South America'],
  },
  {
    id: 'cont-largest',
    category: 'Continents',
    prompt: 'Which is the largest continent?',
    correct: 'Asia',
    choices: ['Asia', 'Africa', 'North America', 'Europe'],
  },
  {
    id: 'cont-antarctica',
    category: 'Continents',
    prompt: 'Which continent is the coldest?',
    correct: 'Antarctica',
    choices: ['Antarctica', 'Europe', 'Asia', 'North America'],
  },
  {
    id: 'country-fuji',
    category: 'Countries',
    prompt: 'Mount Fuji is in which country?',
    correct: 'Japan',
    choices: ['Japan', 'China', 'India', 'Thailand'],
  },
  {
    id: 'country-pyramids',
    category: 'Countries',
    prompt: 'The Great Pyramids of Giza are in which country?',
    correct: 'Egypt',
    choices: ['Egypt', 'Mexico', 'Greece', 'Italy'],
  },
  {
    id: 'country-kangaroo',
    category: 'Countries',
    prompt: 'Kangaroos are native to which country?',
    correct: 'Australia',
    choices: ['Australia', 'South Africa', 'Brazil', 'India'],
  },
  {
    id: 'country-maple',
    category: 'Countries',
    prompt: 'Which country is famous for maple syrup and a maple leaf on its flag?',
    correct: 'Canada',
    choices: ['Canada', 'USA', 'Sweden', 'Switzerland'],
  },
  {
    id: 'country-pizza',
    category: 'Countries',
    prompt: 'Pizza first became famous in which country?',
    correct: 'Italy',
    choices: ['Italy', 'France', 'Greece', 'Spain'],
  },
  {
    id: 'country-amazon-nation',
    category: 'Countries',
    prompt: 'Most of the Amazon rainforest is in which country?',
    correct: 'Brazil',
    choices: ['Brazil', 'Peru', 'Mexico', 'Argentina'],
  },
  {
    id: 'country-safari',
    category: 'Countries',
    prompt: 'The Maasai Mara wildlife reserve is in which country?',
    correct: 'Kenya',
    choices: ['Kenya', 'Egypt', 'India', 'Spain'],
  },
  {
    id: 'country-taj',
    category: 'Countries',
    prompt: 'The Taj Mahal is in which country?',
    correct: 'India',
    choices: ['India', 'Pakistan', 'Iran', 'Turkey'],
  },

  // Oceans
  {
    id: 'ocean-atlantic',
    category: 'Oceans',
    prompt: 'Which ocean is between Europe and North America?',
    correct: 'Atlantic',
    choices: ['Atlantic', 'Pacific', 'Indian', 'Arctic'],
  },
  {
    id: 'ocean-pacific',
    category: 'Oceans',
    prompt: 'Which is the largest ocean on Earth?',
    correct: 'Pacific',
    choices: ['Pacific', 'Atlantic', 'Indian', 'Arctic'],
  },
  {
    id: 'ocean-indian',
    category: 'Oceans',
    prompt: 'Which ocean lies between Africa, India and Australia?',
    correct: 'Indian Ocean',
    choices: ['Indian Ocean', 'Atlantic', 'Arctic', 'Southern Ocean'],
  },
  {
    id: 'ocean-arctic',
    category: 'Oceans',
    prompt: 'Which ocean is around the North Pole?',
    correct: 'Arctic Ocean',
    choices: ['Arctic Ocean', 'Southern Ocean', 'Pacific', 'Atlantic'],
  },
  {
    id: 'ocean-count',
    category: 'Oceans',
    prompt: 'How many oceans are there usually named on a world map?',
    correct: '5',
    choices: ['5', '3', '4', '7'],
    fact: 'Pacific, Atlantic, Indian, Arctic and Southern (Antarctic).',
  },
  {
    id: 'ocean-pacific-place',
    category: 'Oceans',
    prompt: 'Which ocean is between Asia and the Americas?',
    correct: 'Pacific',
    choices: ['Pacific', 'Atlantic', 'Indian', 'Arctic'],
  },
  {
    id: 'ocean-southern',
    category: 'Oceans',
    prompt: 'Which ocean surrounds Antarctica?',
    correct: 'Southern Ocean',
    choices: ['Southern Ocean', 'Arctic Ocean', 'Indian Ocean', 'Caspian Sea'],
  },
  {
    id: 'ocean-saltiest-not',
    category: 'Oceans',
    prompt: 'Which of these is a sea, not an ocean?',
    correct: 'Mediterranean',
    choices: ['Mediterranean', 'Pacific', 'Atlantic', 'Indian'],
  },

  // Flags
  {
    id: 'flag-japan',
    category: 'Flags',
    prompt: 'Which country’s flag is a red circle on a white background?',
    correct: 'Japan',
    choices: ['Japan', 'Bangladesh', 'Switzerland', 'Canada'],
  },
  {
    id: 'flag-canada',
    category: 'Flags',
    prompt: 'Which country’s flag is red and white with a maple leaf?',
    correct: 'Canada',
    choices: ['Canada', 'USA', 'Switzerland', 'Denmark'],
  },
  {
    id: 'flag-usa',
    category: 'Flags',
    prompt: 'The flag with stars and stripes belongs to which country?',
    correct: 'United States',
    choices: ['United States', 'United Kingdom', 'Australia', 'Liberia'],
  },
  {
    id: 'flag-uk',
    category: 'Flags',
    prompt: 'The Union Jack is the flag of which country?',
    correct: 'United Kingdom',
    choices: ['United Kingdom', 'France', 'New Zealand', 'Greece'],
  },
  {
    id: 'flag-france',
    category: 'Flags',
    prompt: 'Which country’s flag is a blue, white and red vertical tricolour?',
    correct: 'France',
    choices: ['France', 'Italy', 'Ireland', 'Russia'],
  },
  {
    id: 'flag-italy',
    category: 'Flags',
    prompt: 'Which country’s flag is green, white and red in vertical stripes?',
    correct: 'Italy',
    choices: ['Italy', 'Mexico', 'Hungary', 'Ireland'],
  },
  {
    id: 'flag-germany',
    category: 'Flags',
    prompt: 'Which country’s flag has horizontal stripes of black, red and gold?',
    correct: 'Germany',
    choices: ['Germany', 'Belgium', 'Spain', 'Austria'],
  },
  {
    id: 'flag-brazil',
    category: 'Flags',
    prompt: 'Which country’s flag is green with a yellow diamond and a blue globe?',
    correct: 'Brazil',
    choices: ['Brazil', 'Portugal', 'Jamaica', 'South Africa'],
  },
  {
    id: 'flag-switzerland',
    category: 'Flags',
    prompt: 'Which country’s flag is a white cross on a red square?',
    correct: 'Switzerland',
    choices: ['Switzerland', 'Denmark', 'England', 'Canada'],
  },
  {
    id: 'flag-india',
    category: 'Flags',
    prompt: 'Which country’s flag has a blue wheel (Ashoka Chakra) in the centre?',
    correct: 'India',
    choices: ['India', 'Pakistan', 'Bangladesh', 'Nepal'],
  },
  {
    id: 'flag-sweden',
    category: 'Flags',
    prompt: 'Which Nordic country’s flag is a yellow cross on a blue background?',
    correct: 'Sweden',
    choices: ['Sweden', 'Norway', 'Finland', 'Denmark'],
  },
  {
    id: 'flag-china',
    category: 'Flags',
    prompt: 'Which country’s flag is red with five yellow stars?',
    correct: 'China',
    choices: ['China', 'Vietnam', 'Turkey', 'Morocco'],
  },

  // Landmarks
  {
    id: 'land-eiffel',
    category: 'Landmarks',
    prompt: 'The Eiffel Tower is in which city?',
    correct: 'Paris',
    choices: ['Paris', 'London', 'Rome', 'Madrid'],
  },
  {
    id: 'land-statue-liberty',
    category: 'Landmarks',
    prompt: 'The Statue of Liberty stands in which city?',
    correct: 'New York',
    choices: ['New York', 'Washington, D.C.', 'Boston', 'Philadelphia'],
  },
  {
    id: 'land-colosseum',
    category: 'Landmarks',
    prompt: 'The Colosseum is in which city?',
    correct: 'Rome',
    choices: ['Rome', 'Athens', 'Paris', 'Cairo'],
  },
  {
    id: 'land-great-wall',
    category: 'Landmarks',
    prompt: 'The Great Wall is in which country?',
    correct: 'China',
    choices: ['China', 'Japan', 'Mongolia', 'India'],
  },
  {
    id: 'land-big-ben',
    category: 'Landmarks',
    prompt: 'Big Ben is a famous clock in which city?',
    correct: 'London',
    choices: ['London', 'Paris', 'Dublin', 'Edinburgh'],
  },
  {
    id: 'land-sydney',
    category: 'Landmarks',
    prompt: 'The Sydney Opera House is in which country?',
    correct: 'Australia',
    choices: ['Australia', 'New Zealand', 'USA', 'Canada'],
  },
  {
    id: 'land-christ',
    category: 'Landmarks',
    prompt: 'Christ the Redeemer overlooks which city?',
    correct: 'Rio de Janeiro',
    choices: ['Rio de Janeiro', 'São Paulo', 'Lisbon', 'Buenos Aires'],
  },
  {
    id: 'land-machu',
    category: 'Landmarks',
    prompt: 'Machu Picchu is an ancient city in which country?',
    correct: 'Peru',
    choices: ['Peru', 'Mexico', 'Chile', 'Bolivia'],
  },
  {
    id: 'land-petra',
    category: 'Landmarks',
    prompt: 'The ancient city of Petra is in which country?',
    correct: 'Jordan',
    choices: ['Jordan', 'Egypt', 'Greece', 'Italy'],
  },
  {
    id: 'land-sagrada',
    category: 'Landmarks',
    prompt: 'The Sagrada Família church is in which city?',
    correct: 'Barcelona',
    choices: ['Barcelona', 'Madrid', 'Rome', 'Lisbon'],
  },
  {
    id: 'land-niagara',
    category: 'Landmarks',
    prompt: 'Niagara Falls lies on the border of the USA and which country?',
    correct: 'Canada',
    choices: ['Canada', 'Mexico', 'Greenland', 'France'],
  },
  {
    id: 'land-acropolis',
    category: 'Landmarks',
    prompt: 'The Acropolis is in which city?',
    correct: 'Athens',
    choices: ['Athens', 'Rome', 'Istanbul', 'Cairo'],
  },

  // Rivers
  {
    id: 'river-nile',
    category: 'Rivers',
    prompt: 'Which river is the longest in Africa?',
    correct: 'Nile',
    choices: ['Nile', 'Amazon', 'Congo', 'Niger'],
  },
  {
    id: 'river-amazon',
    category: 'Rivers',
    prompt: 'Which huge river flows through the rainforest of South America?',
    correct: 'Amazon',
    choices: ['Amazon', 'Nile', 'Mississippi', 'Yangtze'],
  },
  {
    id: 'river-thames',
    category: 'Rivers',
    prompt: 'Which river flows through London?',
    correct: 'Thames',
    choices: ['Thames', 'Seine', 'Rhine', 'Danube'],
  },
  {
    id: 'river-seine',
    category: 'Rivers',
    prompt: 'Which river flows through Paris?',
    correct: 'Seine',
    choices: ['Seine', 'Thames', 'Loire', 'Rhône'],
  },
  {
    id: 'river-mississippi',
    category: 'Rivers',
    prompt: 'Which famous river flows through the central United States?',
    correct: 'Mississippi',
    choices: ['Mississippi', 'Amazon', 'Nile', 'Danube'],
  },
  {
    id: 'river-yangtze',
    category: 'Rivers',
    prompt: 'The Yangtze is a major river in which country?',
    correct: 'China',
    choices: ['China', 'India', 'Japan', 'Vietnam'],
  },
  {
    id: 'river-danube',
    category: 'Rivers',
    prompt: 'The Danube River flows through several countries in which continent?',
    correct: 'Europe',
    choices: ['Europe', 'Asia', 'Africa', 'South America'],
  },
  {
    id: 'river-ganges',
    category: 'Rivers',
    prompt: 'The Ganges is a holy river in which country?',
    correct: 'India',
    choices: ['India', 'Egypt', 'China', 'Italy'],
  },
  {
    id: 'river-nile-egypt',
    category: 'Rivers',
    prompt: 'Ancient Egyptian civilisation grew along which river?',
    correct: 'Nile',
    choices: ['Nile', 'Tigris', 'Amazon', 'Rhine'],
  },
  {
    id: 'river-volga',
    category: 'Rivers',
    prompt: 'The Volga, Europe’s longest river, is in which country?',
    correct: 'Russia',
    choices: ['Russia', 'Germany', 'France', 'Ukraine'],
  },

  // Mountains
  {
    id: 'mt-everest',
    category: 'Mountains',
    prompt: 'What is the highest mountain on Earth?',
    correct: 'Mount Everest',
    choices: ['Mount Everest', 'K2', 'Kilimanjaro', 'Mont Blanc'],
  },
  {
    id: 'mt-everest-range',
    category: 'Mountains',
    prompt: 'Mount Everest is in which mountain range?',
    correct: 'Himalayas',
    choices: ['Himalayas', 'Alps', 'Andes', 'Rockies'],
  },
  {
    id: 'mt-alps',
    category: 'Mountains',
    prompt: 'The Alps are a mountain range in which continent?',
    correct: 'Europe',
    choices: ['Europe', 'Asia', 'Africa', 'North America'],
  },
  {
    id: 'mt-andes',
    category: 'Mountains',
    prompt: 'The Andes mountains run along which continent?',
    correct: 'South America',
    choices: ['South America', 'North America', 'Africa', 'Europe'],
  },
  {
    id: 'mt-kilimanjaro',
    category: 'Mountains',
    prompt: 'Mount Kilimanjaro is in which continent?',
    correct: 'Africa',
    choices: ['Africa', 'Asia', 'South America', 'Europe'],
  },
  {
    id: 'mt-rockies',
    category: 'Mountains',
    prompt: 'The Rocky Mountains are mainly in which country?',
    correct: 'United States',
    choices: ['United States', 'Brazil', 'Australia', 'India'],
    fact: 'They also continue north into Canada.',
  },
  {
    id: 'mt-vesuvius',
    category: 'Mountains',
    prompt: 'Mount Vesuvius, a famous volcano, is in which country?',
    correct: 'Italy',
    choices: ['Italy', 'Greece', 'Japan', 'Mexico'],
  },
  {
    id: 'mt-blanc',
    category: 'Mountains',
    prompt: 'Mont Blanc is one of the highest peaks in which range?',
    correct: 'The Alps',
    choices: ['The Alps', 'The Andes', 'The Rockies', 'The Urals'],
  },
  {
    id: 'mt-fuji-type',
    category: 'Mountains',
    prompt: 'Mount Fuji is a famous example of which landform?',
    correct: 'Volcano',
    choices: ['Volcano', 'Canyon', 'Glacier', 'Island atoll'],
  },
  {
    id: 'mt-table',
    category: 'Mountains',
    prompt: 'Table Mountain looks over which South African city?',
    correct: 'Cape Town',
    choices: ['Cape Town', 'Johannesburg', 'Nairobi', 'Cairo'],
  },

  // European geography
  {
    id: 'eu-med',
    category: 'Europe',
    prompt: 'Which sea lies between southern Europe and North Africa?',
    correct: 'Mediterranean Sea',
    choices: ['Mediterranean Sea', 'Baltic Sea', 'Black Sea', 'Caribbean Sea'],
  },
  {
    id: 'eu-english-channel',
    category: 'Europe',
    prompt: 'The English Channel separates England from which country?',
    correct: 'France',
    choices: ['France', 'Spain', 'Ireland', 'Germany'],
  },
  {
    id: 'eu-iberia',
    category: 'Europe',
    prompt: 'Spain and Portugal share which peninsula?',
    correct: 'Iberian Peninsula',
    choices: ['Iberian Peninsula', 'Balkan Peninsula', 'Italian Peninsula', 'Scandinavian Peninsula'],
  },
  {
    id: 'eu-scandinavia',
    category: 'Europe',
    prompt: 'Norway, Sweden and Denmark are part of which region?',
    correct: 'Scandinavia',
    choices: ['Scandinavia', 'The Balkans', 'The Alps', 'Iberia'],
  },
  {
    id: 'eu-alps-countries',
    category: 'Europe',
    prompt: 'Switzerland is famous for which mountain range?',
    correct: 'The Alps',
    choices: ['The Alps', 'The Andes', 'The Pyrenees', 'The Urals'],
  },
  {
    id: 'eu-rhine',
    category: 'Europe',
    prompt: 'The Rhine is a major river in which continent?',
    correct: 'Europe',
    choices: ['Europe', 'Africa', 'Asia', 'Australia'],
  },
  {
    id: 'eu-vatican',
    category: 'Europe',
    prompt: 'Vatican City is inside which Italian city?',
    correct: 'Rome',
    choices: ['Rome', 'Milan', 'Venice', 'Naples'],
  },
  {
    id: 'eu-baltic',
    category: 'Europe',
    prompt: 'Finland has a long coastline on which sea?',
    correct: 'Baltic Sea',
    choices: ['Baltic Sea', 'Mediterranean Sea', 'Black Sea', 'Red Sea'],
  },
  {
    id: 'eu-greece-islands',
    category: 'Europe',
    prompt: 'Crete is a large island belonging to which country?',
    correct: 'Greece',
    choices: ['Greece', 'Italy', 'Spain', 'Turkey'],
  },
  {
    id: 'eu-danube-city',
    category: 'Europe',
    prompt: 'Budapest, on the Danube, is the capital of which country?',
    correct: 'Hungary',
    choices: ['Hungary', 'Austria', 'Romania', 'Czechia'],
  },
  {
    id: 'eu-netherlands',
    category: 'Europe',
    prompt: 'Amsterdam is the capital of which country?',
    correct: 'The Netherlands',
    choices: ['The Netherlands', 'Belgium', 'Denmark', 'Germany'],
  },
  {
    id: 'eu-prague',
    category: 'Europe',
    prompt: 'Prague is the capital of which country?',
    correct: 'Czechia',
    choices: ['Czechia', 'Poland', 'Austria', 'Slovakia'],
  },

  // World geography
  {
    id: 'world-equator',
    category: 'World',
    prompt: 'The Equator is an imaginary line around the…',
    correct: 'Middle of the Earth',
    choices: ['Middle of the Earth', 'North Pole', 'South Pole', 'Moon'],
  },
  {
    id: 'world-north-pole',
    category: 'World',
    prompt: 'The North Pole is located in which ocean?',
    correct: 'Arctic Ocean',
    choices: ['Arctic Ocean', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean'],
  },
  {
    id: 'world-largest-country',
    category: 'World',
    prompt: 'Which country has the largest land area?',
    correct: 'Russia',
    choices: ['Russia', 'Canada', 'China', 'United States'],
  },
  {
    id: 'world-largest-pop',
    category: 'World',
    prompt: 'Which of these countries has the largest population?',
    correct: 'India',
    choices: ['India', 'USA', 'Brazil', 'Nigeria'],
  },
  {
    id: 'world-sahara',
    category: 'World',
    prompt: 'The Sahara is a huge desert in which continent?',
    correct: 'Africa',
    choices: ['Africa', 'Asia', 'Australia', 'South America'],
  },
  {
    id: 'world-greenland',
    category: 'World',
    prompt: 'Greenland is a large island belonging to which kingdom?',
    correct: 'Denmark',
    choices: ['Denmark', 'Canada', 'Norway', 'Iceland'],
  },
  {
    id: 'world-new-zealand',
    category: 'World',
    prompt: 'New Zealand is made up mainly of how many large islands?',
    correct: 'Two',
    choices: ['Two', 'One', 'Three', 'Five'],
  },
  {
    id: 'world-caribbean',
    category: 'World',
    prompt: 'Cuba is an island in which sea?',
    correct: 'Caribbean Sea',
    choices: ['Caribbean Sea', 'Mediterranean Sea', 'Baltic Sea', 'Red Sea'],
  },
  {
    id: 'world-hawaii',
    category: 'World',
    prompt: 'The Hawaiian Islands are in which ocean?',
    correct: 'Pacific Ocean',
    choices: ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
  },
  {
    id: 'world-suez',
    category: 'World',
    prompt: 'The Suez Canal connects the Mediterranean Sea to which sea?',
    correct: 'Red Sea',
    choices: ['Red Sea', 'Black Sea', 'Caspian Sea', 'North Sea'],
  },
  {
    id: 'world-panama',
    category: 'World',
    prompt: 'The Panama Canal connects the Atlantic Ocean to which ocean?',
    correct: 'Pacific Ocean',
    choices: ['Pacific Ocean', 'Indian Ocean', 'Arctic Ocean', 'Southern Ocean'],
  },
  {
    id: 'world-iceland',
    category: 'World',
    prompt: 'Iceland is an island country in which ocean?',
    correct: 'Atlantic Ocean',
    choices: ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Southern Ocean'],
  },

  // Physical geography
  {
    id: 'phys-island',
    category: 'Physical',
    prompt: 'Land completely surrounded by water is called an…',
    correct: 'Island',
    choices: ['Island', 'Peninsula', 'Isthmus', 'Delta'],
  },
  {
    id: 'phys-peninsula',
    category: 'Physical',
    prompt: 'Land surrounded by water on three sides is called a…',
    correct: 'Peninsula',
    choices: ['Peninsula', 'Island', 'Gulf', 'Plateau'],
  },
  {
    id: 'phys-desert',
    category: 'Physical',
    prompt: 'A very dry place that gets little rain is called a…',
    correct: 'Desert',
    choices: ['Desert', 'Delta', 'Tundra forest', 'Reef'],
  },
  {
    id: 'phys-volcano',
    category: 'Physical',
    prompt: 'A mountain that can erupt lava is called a…',
    correct: 'Volcano',
    choices: ['Volcano', 'Canyon', 'Glacier', 'Dune'],
  },
  {
    id: 'phys-glacier',
    category: 'Physical',
    prompt: 'A slow-moving river of ice is called a…',
    correct: 'Glacier',
    choices: ['Glacier', 'Geyser', 'Delta', 'Reef'],
  },
  {
    id: 'phys-delta',
    category: 'Physical',
    prompt: 'Where a river spreads out as it meets the sea is often called a…',
    correct: 'Delta',
    choices: ['Delta', 'Fjord', 'Plateau', 'Isthmus'],
  },
  {
    id: 'phys-equator-climate',
    category: 'Physical',
    prompt: 'Places near the Equator are generally…',
    correct: 'Warmer',
    choices: ['Warmer', 'Colder', 'Always snowy', 'Always dry deserts'],
  },
  {
    id: 'phys-poles',
    category: 'Physical',
    prompt: 'Places near the North and South Poles are generally…',
    correct: 'Colder',
    choices: ['Colder', 'Warmer', 'Rainforest', 'Tropical'],
  },
  {
    id: 'phys-rainforest',
    category: 'Physical',
    prompt: 'A dense, wet forest near the Equator is called a…',
    correct: 'Rainforest',
    choices: ['Rainforest', 'Tundra', 'Savanna desert', 'Taiga ice sheet'],
  },
  {
    id: 'phys-canyon',
    category: 'Physical',
    prompt: 'The Grand Canyon was carved mainly by which river?',
    correct: 'Colorado River',
    choices: ['Colorado River', 'Mississippi', 'Amazon', 'Nile'],
  },
  {
    id: 'phys-reef',
    category: 'Physical',
    prompt: 'The Great Barrier Reef is off the coast of which country?',
    correct: 'Australia',
    choices: ['Australia', 'Brazil', 'South Africa', 'Japan'],
  },
  {
    id: 'phys-lake',
    category: 'Physical',
    prompt: 'The largest freshwater lake by surface area is Lake Superior in…',
    correct: 'North America',
    choices: ['North America', 'Africa', 'Europe', 'Australia'],
  },
  {
    id: 'phys-compass-n',
    category: 'Physical',
    prompt: 'On most maps, which direction is at the top?',
    correct: 'North',
    choices: ['North', 'South', 'East', 'West'],
  },
  {
    id: 'phys-hemisphere-brazil',
    category: 'Physical',
    prompt: 'Most of Brazil is in which hemisphere?',
    correct: 'Southern Hemisphere',
    choices: ['Southern Hemisphere', 'Northern Hemisphere', 'Eastern only', 'Western ice cap'],
  },
];

export function questionCount(): number {
  return QUESTIONS.length;
}
