import { classicArt, uiIcons } from '../assets';
import { buildObjects } from './build';
import type { Theme } from './types';

export const classicTheme: Theme = {
  id: 'classic',
  name: 'Fruit Classic',
  shortName: 'Classic',
  emoji: '🍎',
  icon: uiIcons.classic,
  background: classicArt.bg,
  tagline: 'Bright orchard merges',
  cssVars: {
    '--bg': '#fff4e5',
    '--bg2': '#fde68a',
    '--text': '#3f2a1d',
    '--muted': '#8a5a3c',
    '--panel': 'rgba(255, 255, 255, 0.72)',
    '--panel-border': 'rgba(180, 83, 9, 0.18)',
    '--accent': '#ea580c',
    '--accent-2': '#16a34a',
    '--danger': '#dc2626',
    '--stage': 'linear-gradient(180deg, #fff7ed 0%, #fed7aa 55%, #fdba74 100%)',
    '--hud': 'rgba(255, 247, 237, 0.92)',
    '--shadow': 'rgba(180, 83, 9, 0.18)',
    '--btn-text': '#fff7ed',
  },
  objects: buildObjects([
    {
      id: 'cherry',
      name: 'Cherry',
      visual: {
        src: classicArt.cherry,
        emoji: '🍒',
        fill: '#e11d48',
        stroke: '#9f1239',
        highlight: '#fb7185',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'strawberry',
      name: 'Strawberry',
      visual: {
        src: classicArt.strawberry,
        emoji: '🍓',
        fill: '#f43f5e',
        stroke: '#be123c',
        highlight: '#fda4af',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'blueberry',
      name: 'Blueberry',
      visual: {
        src: classicArt.blueberry,
        emoji: '🫐',
        fill: '#2563eb',
        stroke: '#1e3a8a',
        highlight: '#93c5fd',
        style: 'fruit',
      },
    },
    {
      id: 'grape',
      name: 'Grape',
      visual: {
        src: classicArt.grape,
        emoji: '🍇',
        fill: '#7c3aed',
        stroke: '#5b21b6',
        highlight: '#c4b5fd',
        style: 'fruit',
      },
    },
    {
      id: 'lime',
      name: 'Lime',
      visual: {
        src: classicArt.lime,
        emoji: '🍋',
        fill: '#84cc16',
        stroke: '#3f6212',
        highlight: '#d9f99d',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'orange',
      name: 'Orange',
      visual: {
        src: classicArt.orange,
        emoji: '🍊',
        fill: '#fb923c',
        stroke: '#c2410c',
        highlight: '#fed7aa',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'apple',
      name: 'Apple',
      visual: {
        src: classicArt.apple,
        emoji: '🍎',
        fill: '#ef4444',
        stroke: '#b91c1c',
        highlight: '#fca5a5',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'pear',
      name: 'Pear',
      visual: {
        src: classicArt.pear,
        emoji: '🍐',
        fill: '#a3e635',
        stroke: '#4d7c0f',
        highlight: '#d9f99d',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'peach',
      name: 'Peach',
      visual: {
        src: classicArt.peach,
        emoji: '🍑',
        fill: '#fb7185',
        stroke: '#e11d48',
        highlight: '#fecdd3',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'pineapple',
      name: 'Pineapple',
      visual: {
        src: classicArt.pineapple,
        emoji: '🍍',
        fill: '#f59e0b',
        stroke: '#b45309',
        highlight: '#fde68a',
        style: 'fruit',
        leaf: true,
      },
    },
    {
      id: 'watermelon',
      name: 'Watermelon',
      visual: {
        src: classicArt.watermelon,
        emoji: '🍉',
        fill: '#22c55e',
        stroke: '#166534',
        highlight: '#86efac',
        style: 'fruit',
      },
    },
  ]),
};
