import { drinksArt, uiIcons } from '../assets';
import { buildObjects } from './build';
import type { Theme } from './types';

export const drinksTheme: Theme = {
  id: 'drinks',
  name: 'Nightcap Bar',
  shortName: 'Drinks',
  emoji: '🍸',
  icon: uiIcons.drinks,
  background: drinksArt.bg,
  tagline: 'Stylized glasses, no labels',
  cssVars: {
    '--bg': '#1c1016',
    '--bg2': '#3b1224',
    '--text': '#fef3c7',
    '--muted': '#e8c07a',
    '--panel': 'rgba(40, 20, 28, 0.78)',
    '--panel-border': 'rgba(232, 192, 122, 0.28)',
    '--accent': '#e8c07a',
    '--accent-2': '#fb7185',
    '--danger': '#fda4af',
    '--stage': 'linear-gradient(180deg, #2a151c 0%, #3b1224 45%, #1c1016 100%)',
    '--hud': 'rgba(28, 16, 22, 0.9)',
    '--shadow': 'rgba(232, 192, 122, 0.16)',
    '--btn-text': '#1c1016',
  },
  objects: buildObjects([
    {
      id: 'ice',
      name: 'Ice cube',
      visual: {
        src: drinksArt.ice,
        emoji: '🧊',
        fill: '#38bdf8',
        stroke: '#7dd3fc',
        highlight: '#e0f2fe',
        style: 'drink',
        drink: 'shot',
      },
    },
    {
      id: 'olive',
      name: 'Olive',
      visual: {
        src: drinksArt.olive,
        emoji: '🫒',
        fill: '#65a30d',
        stroke: '#3f6212',
        highlight: '#bef264',
        style: 'drink',
        drink: 'beer-small',
      },
    },
    {
      id: 'shot',
      name: 'Shot glass',
      visual: {
        src: drinksArt.shot,
        emoji: '🥃',
        fill: '#f59e0b',
        stroke: '#e8c07a',
        highlight: '#fde68a',
        style: 'drink',
        drink: 'shot',
      },
    },
    {
      id: 'wine-glass',
      name: 'Wine glass',
      visual: {
        src: drinksArt.wine,
        emoji: '🍷',
        fill: '#9f1239',
        stroke: '#e8c07a',
        highlight: '#fb7185',
        style: 'drink',
        drink: 'wine-glass',
      },
    },
    {
      id: 'martini',
      name: 'Martini',
      visual: {
        src: drinksArt.martini,
        emoji: '🍸',
        fill: '#e5e7eb',
        stroke: '#e8c07a',
        highlight: '#ffffff',
        style: 'drink',
        drink: 'martini',
      },
    },
    {
      id: 'whiskey',
      name: 'Whiskey',
      visual: {
        src: drinksArt.whiskey,
        emoji: '🥃',
        fill: '#b45309',
        stroke: '#e8c07a',
        highlight: '#fdba74',
        style: 'drink',
        drink: 'whiskey',
      },
    },
    {
      id: 'cocktail',
      name: 'Cocktail',
      visual: {
        src: drinksArt.cocktail,
        emoji: '🍹',
        fill: '#fb923c',
        stroke: '#e8c07a',
        highlight: '#fed7aa',
        style: 'drink',
        drink: 'cocktail',
      },
    },
    {
      id: 'margarita',
      name: 'Margarita',
      visual: {
        src: drinksArt.margarita,
        emoji: '🍸',
        fill: '#84cc16',
        stroke: '#e8c07a',
        highlight: '#d9f99d',
        style: 'drink',
        drink: 'pint',
      },
    },
    {
      id: 'mojito',
      name: 'Mojito',
      visual: {
        src: drinksArt.mojito,
        emoji: '🌿',
        fill: '#86efac',
        stroke: '#e8c07a',
        highlight: '#ecfccb',
        style: 'drink',
        drink: 'pitcher',
      },
    },
    {
      id: 'champagne',
      name: 'Champagne',
      visual: {
        src: drinksArt.champagne,
        emoji: '🥂',
        fill: '#facc15',
        stroke: '#e8c07a',
        highlight: '#fef9c3',
        style: 'drink',
        drink: 'champagne',
      },
    },
    {
      id: 'bottle',
      name: 'Celebration bottle',
      visual: {
        src: drinksArt.bottle,
        emoji: '🍾',
        fill: '#166534',
        stroke: '#e8c07a',
        highlight: '#86efac',
        style: 'drink',
        drink: 'wine-bottle',
      },
    },
  ]),
};
