import { buildObjects } from './build';
import type { Theme } from './types';

export const drinksTheme: Theme = {
  id: 'drinks',
  name: 'Nightcap Bar',
  shortName: 'Drinks',
  emoji: '🍸',
  tagline: 'Stylized glasses, no labels',
  cssVars: {
    '--bg': '#1c1016',
    '--bg2': '#3b1224',
    '--text': '#fef3c7',
    '--muted': '#e8c07a',
    '--panel': 'rgba(40, 20, 28, 0.78)',
    '--panel-border': 'rgba(232, 192, 122, 0.28)',
    '--accent': '#e8c07a',
    '--accent-2': '#fb7185',
    '--danger': '#fda4af',
    '--stage': 'linear-gradient(180deg, #2a151c 0%, #3b1224 45%, #1c1016 100%)',
    '--hud': 'rgba(28, 16, 22, 0.9)',
    '--shadow': 'rgba(232, 192, 122, 0.16)',
    '--btn-text': '#1c1016',
  },
  objects: buildObjects([
    {
      id: 'shot',
      name: 'Shot',
      visual: {
        emoji: '🥃',
        fill: '#f59e0b',
        stroke: '#e8c07a',
        highlight: '#fde68a',
        style: 'drink',
        drink: 'shot',
      },
    },
    {
      id: 'beer-small',
      name: 'Small beer',
      visual: {
        emoji: '🍺',
        fill: '#fbbf24',
        stroke: '#e8c07a',
        highlight: '#fef3c7',
        style: 'drink',
        drink: 'beer-small',
      },
    },
    {
      id: 'whiskey',
      name: 'Whiskey glass',
      visual: {
        emoji: '🥃',
        fill: '#b45309',
        stroke: '#e8c07a',
        highlight: '#fdba74',
        style: 'drink',
        drink: 'whiskey',
      },
    },
    {
      id: 'wine-glass',
      name: 'Wine glass',
      visual: {
        emoji: '🍷',
        fill: '#9f1239',
        stroke: '#e8c07a',
        highlight: '#fb7185',
        style: 'drink',
        drink: 'wine-glass',
      },
    },
    {
      id: 'martini',
      name: 'Martini',
      visual: {
        emoji: '🍸',
        fill: '#e5e7eb',
        stroke: '#e8c07a',
        highlight: '#ffffff',
        style: 'drink',
        drink: 'martini',
      },
    },
    {
      id: 'cocktail',
      name: 'Cocktail',
      visual: {
        emoji: '🍹',
        fill: '#fb7185',
        stroke: '#e8c07a',
        highlight: '#fecdd3',
        style: 'drink',
        drink: 'cocktail',
      },
    },
    {
      id: 'pint',
      name: 'Pint',
      visual: {
        emoji: '🍻',
        fill: '#d97706',
        stroke: '#e8c07a',
        highlight: '#fde68a',
        style: 'drink',
        drink: 'pint',
      },
    },
    {
      id: 'wine-bottle',
      name: 'Wine bottle',
      visual: {
        emoji: '🍾',
        fill: '#14532d',
        stroke: '#e8c07a',
        highlight: '#86efac',
        style: 'drink',
        drink: 'wine-bottle',
      },
    },
    {
      id: 'champagne',
      name: 'Champagne bottle',
      visual: {
        emoji: '🥂',
        fill: '#854d0e',
        stroke: '#e8c07a',
        highlight: '#fde68a',
        style: 'drink',
        drink: 'champagne',
      },
    },
    {
      id: 'pitcher',
      name: 'Cocktail pitcher',
      visual: {
        emoji: '🧋',
        fill: '#be123c',
        stroke: '#e8c07a',
        highlight: '#fda4af',
        style: 'drink',
        drink: 'pitcher',
      },
    },
    {
      id: 'punch',
      name: 'Party punch',
      visual: {
        emoji: '🧃',
        fill: '#e11d48',
        stroke: '#e8c07a',
        highlight: '#fecdd3',
        style: 'drink',
        drink: 'punch',
      },
    },
  ]),
};
