import { nightArt, uiIcons } from '../assets';
import { buildObjects } from './build';
import type { Theme } from './types';

export const nightTheme: Theme = {
  id: 'night',
  name: 'Fruit Night',
  shortName: 'Night',
  emoji: '🌙',
  icon: uiIcons.night,
  background: nightArt.bg,
  tagline: 'Neon fruit after dark',
  cssVars: {
    '--bg': '#07091a',
    '--bg2': '#1e1b4b',
    '--text': '#e0e7ff',
    '--muted': '#a5b4fc',
    '--panel': 'rgba(15, 23, 42, 0.78)',
    '--panel-border': 'rgba(129, 140, 248, 0.28)',
    '--accent': '#22d3ee',
    '--accent-2': '#e879f9',
    '--danger': '#fb7185',
    '--stage': 'linear-gradient(180deg, #020617 0%, #1e1b4b 50%, #312e81 100%)',
    '--hud': 'rgba(2, 6, 23, 0.88)',
    '--shadow': 'rgba(34, 211, 238, 0.18)',
    '--btn-text': '#042f2e',
  },
  objects: buildObjects([
    {
      id: 'cherry',
      name: 'Cherry',
      visual: {
        src: nightArt.cherry,
        emoji: '🍒',
        fill: '#9f1239',
        stroke: '#fb7185',
        highlight: '#fda4af',
        style: 'night-fruit',
        glow: '#fb7185',
      },
    },
    {
      id: 'strawberry',
      name: 'Strawberry',
      visual: {
        src: nightArt.strawberry,
        emoji: '🍓',
        fill: '#be123c',
        stroke: '#fb7185',
        highlight: '#fda4af',
        style: 'night-fruit',
        glow: '#fb7185',
      },
    },
    {
      id: 'blueberry',
      name: 'Blueberry',
      visual: {
        src: nightArt.blueberry,
        emoji: '🫐',
        fill: '#1d4ed8',
        stroke: '#22d3ee',
        highlight: '#67e8f9',
        style: 'night-fruit',
        glow: '#22d3ee',
      },
    },
    {
      id: 'grape',
      name: 'Grape',
      visual: {
        src: nightArt.grape,
        emoji: '🍇',
        fill: '#6b21a8',
        stroke: '#e879f9',
        highlight: '#f0abfc',
        style: 'night-fruit',
        glow: '#e879f9',
      },
    },
    {
      id: 'lime',
      name: 'Lime',
      visual: {
        src: nightArt.lime,
        emoji: '🍋',
        fill: '#3f6212',
        stroke: '#a3e635',
        highlight: '#d9f99d',
        style: 'night-fruit',
        glow: '#a3e635',
      },
    },
    {
      id: 'orange',
      name: 'Orange',
      visual: {
        src: nightArt.orange,
        emoji: '🍊',
        fill: '#c2410c',
        stroke: '#fb923c',
        highlight: '#fdba74',
        style: 'night-fruit',
        glow: '#fb923c',
      },
    },
    {
      id: 'apple',
      name: 'Apple',
      visual: {
        src: nightArt.apple,
        emoji: '🍎',
        fill: '#b91c1c',
        stroke: '#fb7185',
        highlight: '#fecaca',
        style: 'night-fruit',
        glow: '#fb7185',
      },
    },
    {
      id: 'pear',
      name: 'Pear',
      visual: {
        src: nightArt.pear,
        emoji: '🍐',
        fill: '#3f6212',
        stroke: '#a3e635',
        highlight: '#bef264',
        style: 'night-fruit',
        glow: '#a3e635',
      },
    },
    {
      id: 'peach',
      name: 'Peach',
      visual: {
        src: nightArt.peach,
        emoji: '🍑',
        fill: '#9d174d',
        stroke: '#f9a8d4',
        highlight: '#fbcfe8',
        style: 'night-fruit',
        glow: '#f9a8d4',
      },
    },
    {
      id: 'pineapple',
      name: 'Pineapple',
      visual: {
        src: nightArt.pineapple,
        emoji: '🍍',
        fill: '#b45309',
        stroke: '#facc15',
        highlight: '#fde68a',
        style: 'night-fruit',
        glow: '#facc15',
      },
    },
    {
      id: 'watermelon',
      name: 'Watermelon',
      visual: {
        src: nightArt.watermelon,
        emoji: '🍉',
        fill: '#0f766e',
        stroke: '#5eead4',
        highlight: '#99f6e4',
        style: 'night-fruit',
        glow: '#5eead4',
      },
    },
  ]),
};
