import { buildObjects } from './build';
import type { Theme } from './types';

export const nightTheme: Theme = {
  id: 'night',
  name: 'Fruit Night',
  shortName: 'Night',
  emoji: '🌙',
  tagline: 'Neon fruit after dark',
  cssVars: {
    '--bg': '#07091a',
    '--bg2': '#1e1b4b',
    '--text': '#e0e7ff',
    '--muted': '#a5b4fc',
    '--panel': 'rgba(15, 23, 42, 0.78)',
    '--panel-border': 'rgba(129, 140, 248, 0.28)',
    '--accent': '#22d3ee',
    '--accent-2': '#e879f9',
    '--danger': '#fb7185',
    '--stage': 'linear-gradient(180deg, #020617 0%, #1e1b4b 50%, #312e81 100%)',
    '--hud': 'rgba(2, 6, 23, 0.88)',
    '--shadow': 'rgba(34, 211, 238, 0.18)',
    '--btn-text': '#042f2e',
  },
  objects: buildObjects([
    {
      id: 'blueberry',
      name: 'Blueberry',
      visual: {
        emoji: '🫐',
        fill: '#1d4ed8',
        stroke: '#22d3ee',
        highlight: '#93c5fd',
        style: 'night-fruit',
        glow: '#22d3ee',
      },
    },
    {
      id: 'raspberry',
      name: 'Raspberry',
      visual: {
        emoji: '🍇',
        fill: '#9d174d',
        stroke: '#fb7185',
        highlight: '#f9a8d4',
        style: 'night-fruit',
        glow: '#fb7185',
      },
    },
    {
      id: 'plum',
      name: 'Plum',
      visual: {
        emoji: '🟣',
        fill: '#6b21a8',
        stroke: '#e879f9',
        highlight: '#d8b4fe',
        style: 'night-fruit',
        glow: '#e879f9',
      },
    },
    {
      id: 'kiwi',
      name: 'Kiwi',
      visual: {
        emoji: '🥝',
        fill: '#365314',
        stroke: '#a3e635',
        highlight: '#bef264',
        style: 'night-fruit',
        glow: '#a3e635',
      },
    },
    {
      id: 'fig',
      name: 'Fig',
      visual: {
        emoji: '🟣',
        fill: '#4c1d95',
        stroke: '#c4b5fd',
        highlight: '#ddd6fe',
        style: 'night-fruit',
        glow: '#c4b5fd',
      },
    },
    {
      id: 'pomegranate',
      name: 'Pomegranate',
      visual: {
        emoji: '🍎',
        fill: '#7f1d1d',
        stroke: '#fb7185',
        highlight: '#fecaca',
        style: 'night-fruit',
        glow: '#fb7185',
      },
    },
    {
      id: 'mango',
      name: 'Mango',
      visual: {
        emoji: '🥭',
        fill: '#9a3412',
        stroke: '#fb923c',
        highlight: '#fdba74',
        style: 'night-fruit',
        glow: '#fb923c',
      },
    },
    {
      id: 'papaya',
      name: 'Papaya',
      visual: {
        emoji: '🧡',
        fill: '#7c2d12',
        stroke: '#fdba74',
        highlight: '#fed7aa',
        style: 'night-fruit',
        glow: '#fdba74',
      },
    },
    {
      id: 'coconut',
      name: 'Coconut',
      visual: {
        emoji: '🥥',
        fill: '#1c1917',
        stroke: '#e7e5e4',
        highlight: '#a8a29e',
        style: 'night-fruit',
        glow: '#e7e5e4',
      },
    },
    {
      id: 'dragonfruit',
      name: 'Dragon fruit',
      visual: {
        emoji: '🐉',
        fill: '#831843',
        stroke: '#f9a8d4',
        highlight: '#fbcfe8',
        style: 'night-fruit',
        glow: '#f9a8d4',
      },
    },
    {
      id: 'moon-melon',
      name: 'Moon melon',
      visual: {
        emoji: '🍈',
        fill: '#0f766e',
        stroke: '#5eead4',
        highlight: '#99f6e4',
        style: 'night-fruit',
        glow: '#5eead4',
      },
    },
  ]),
};
