import { sportsArt, uiIcons } from '../assets';
import { buildObjects } from './build';
import type { Theme } from './types';

export const sportsTheme: Theme = {
  id: 'sports',
  name: 'Sports Arena',
  shortName: 'Sports',
  emoji: '⚽',
  icon: uiIcons.sports,
  background: sportsArt.bg,
  tagline: 'Stadium lights and big plays',
  cssVars: {
    '--bg': '#052e16',
    '--bg2': '#14532d',
    '--text': '#f7fee7',
    '--muted': '#bef264',
    '--panel': 'rgba(20, 83, 45, 0.7)',
    '--panel-border': 'rgba(190, 242, 100, 0.28)',
    '--accent': '#eab308',
    '--accent-2': '#22c55e',
    '--danger': '#f87171',
    '--stage': 'linear-gradient(180deg, #14532d 0%, #166534 40%, #15803d 70%, #3f6212 100%)',
    '--hud': 'rgba(5, 46, 22, 0.86)',
    '--shadow': 'rgba(234, 179, 8, 0.22)',
    '--btn-text': '#14532d',
  },
  objects: buildObjects([
    {
      id: 'pingpong',
      name: 'Ping-pong ball',
      visual: {
        src: sportsArt.pingpong,
        emoji: '🏓',
        fill: '#f97316',
        stroke: '#9a3412',
        highlight: '#fdba74',
        style: 'ball',
        ball: 'pingpong',
      },
    },
    {
      id: 'golf',
      name: 'Golf ball',
      visual: {
        src: sportsArt.golf,
        emoji: '⛳',
        fill: '#f1f5f9',
        stroke: '#94a3b8',
        highlight: '#ffffff',
        style: 'ball',
        ball: 'golf',
      },
    },
    {
      id: 'pool',
      name: '8-ball',
      visual: {
        src: sportsArt.eightball,
        emoji: '🎱',
        fill: '#0f172a',
        stroke: '#020617',
        highlight: '#64748b',
        style: 'ball',
        ball: 'pool',
        number: '8',
      },
    },
    {
      id: 'tennis',
      name: 'Tennis ball',
      visual: {
        src: sportsArt.tennis,
        emoji: '🎾',
        fill: '#a3e635',
        stroke: '#ffffff',
        highlight: '#ecfccb',
        style: 'ball',
        ball: 'tennis',
      },
    },
    {
      id: 'baseball',
      name: 'Baseball',
      visual: {
        src: sportsArt.baseball,
        emoji: '⚾',
        fill: '#fff7ed',
        stroke: '#ef4444',
        highlight: '#ffffff',
        style: 'ball',
        ball: 'baseball',
      },
    },
    {
      id: 'bowling',
      name: 'Bowling ball',
      visual: {
        src: sportsArt.bowling,
        emoji: '🎳',
        fill: '#7c3aed',
        stroke: '#2e1065',
        highlight: '#c4b5fd',
        style: 'ball',
        ball: 'bowling',
      },
    },
    {
      id: 'football',
      name: 'American football',
      visual: {
        src: sportsArt.football,
        emoji: '🏈',
        fill: '#92400e',
        stroke: '#451a03',
        highlight: '#d6a07a',
        style: 'ball',
        ball: 'handball',
      },
    },
    {
      id: 'volleyball',
      name: 'Volleyball',
      visual: {
        src: sportsArt.volleyball,
        emoji: '🏐',
        fill: '#fff7ed',
        stroke: '#f97316',
        highlight: '#ffffff',
        style: 'ball',
        ball: 'volleyball',
      },
    },
    {
      id: 'basketball',
      name: 'Basketball',
      visual: {
        src: sportsArt.basketball,
        emoji: '🏀',
        fill: '#ea580c',
        stroke: '#111827',
        highlight: '#fdba74',
        style: 'ball',
        ball: 'basketball',
      },
    },
    {
      id: 'soccer',
      name: 'Soccer ball',
      visual: {
        src: sportsArt.soccer,
        emoji: '⚽',
        fill: '#f8fafc',
        stroke: '#111827',
        highlight: '#e2e8f0',
        style: 'ball',
        ball: 'soccer',
      },
    },
    {
      id: 'championship',
      name: 'Championship ball',
      visual: {
        src: sportsArt.trophy,
        emoji: '🏆',
        fill: '#eab308',
        stroke: '#854d0e',
        highlight: '#fef08a',
        style: 'ball',
        ball: 'championship',
      },
    },
  ]),
};
