import { buildObjects } from './build';
import type { Theme } from './types';

export const sportsTheme: Theme = {
  id: 'sports',
  name: 'Sports Arena',
  shortName: 'Sports',
  emoji: '⚽',
  tagline: 'Stadium lights and big plays',
  cssVars: {
    '--bg': '#052e16',
    '--bg2': '#14532d',
    '--text': '#f7fee7',
    '--muted': '#bef264',
    '--panel': 'rgba(20, 83, 45, 0.7)',
    '--panel-border': 'rgba(190, 242, 100, 0.28)',
    '--accent': '#eab308',
    '--accent-2': '#22c55e',
    '--danger': '#f87171',
    '--stage': 'linear-gradient(180deg, #14532d 0%, #166534 40%, #15803d 70%, #3f6212 100%)',
    '--hud': 'rgba(5, 46, 22, 0.86)',
    '--shadow': 'rgba(234, 179, 8, 0.22)',
    '--btn-text': '#14532d',
  },
  objects: buildObjects([
    {
      id: 'pingpong',
      name: 'Ping-pong ball',
      visual: {
        emoji: '🏓',
        fill: '#f8fafc',
        stroke: '#cbd5e1',
        highlight: '#ffffff',
        style: 'ball',
        ball: 'pingpong',
      },
    },
    {
      id: 'golf',
      name: 'Golf ball',
      visual: {
        emoji: '⛳',
        fill: '#f1f5f9',
        stroke: '#94a3b8',
        highlight: '#ffffff',
        style: 'ball',
        ball: 'golf',
      },
    },
    {
      id: 'pool',
      name: 'Pool ball',
      visual: {
        emoji: '🎱',
        fill: '#dc2626',
        stroke: '#111827',
        highlight: '#fca5a5',
        style: 'ball',
        ball: 'pool',
        number: '3',
      },
    },
    {
      id: 'tennis',
      name: 'Tennis ball',
      visual: {
        emoji: '🎾',
        fill: '#d9f99d',
        stroke: '#ffffff',
        highlight: '#ecfccb',
        style: 'ball',
        ball: 'tennis',
      },
    },
    {
      id: 'baseball',
      name: 'Baseball',
      visual: {
        emoji: '⚾',
        fill: '#fff7ed',
        stroke: '#ef4444',
        highlight: '#ffffff',
        style: 'ball',
        ball: 'baseball',
      },
    },
    {
      id: 'handball',
      name: 'Handball',
      visual: {
        emoji: '🤾',
        fill: '#2563eb',
        stroke: '#1e3a8a',
        highlight: '#93c5fd',
        style: 'ball',
        ball: 'handball',
      },
    },
    {
      id: 'volleyball',
      name: 'Volleyball',
      visual: {
        emoji: '🏐',
        fill: '#fff7ed',
        stroke: '#f97316',
        highlight: '#ffffff',
        style: 'ball',
        ball: 'volleyball',
      },
    },
    {
      id: 'soccer',
      name: 'Football',
      visual: {
        emoji: '⚽',
        fill: '#f8fafc',
        stroke: '#111827',
        highlight: '#e2e8f0',
        style: 'ball',
        ball: 'soccer',
      },
    },
    {
      id: 'basketball',
      name: 'Basketball',
      visual: {
        emoji: '🏀',
        fill: '#ea580c',
        stroke: '#111827',
        highlight: '#fdba74',
        style: 'ball',
        ball: 'basketball',
      },
    },
    {
      id: 'bowling',
      name: 'Bowling ball',
      visual: {
        emoji: '🎳',
        fill: '#1e293b',
        stroke: '#0f172a',
        highlight: '#64748b',
        style: 'ball',
        ball: 'bowling',
      },
    },
    {
      id: 'championship',
      name: 'Championship ball',
      visual: {
        emoji: '🏆',
        fill: '#eab308',
        stroke: '#854d0e',
        highlight: '#fef08a',
        style: 'ball',
        ball: 'championship',
      },
    },
  ]),
};
