import { tropicalArt, uiIcons } from '../assets';
import { buildObjects } from './build';
import type { Theme } from './types';

export const tropicalTheme: Theme = {
  id: 'tropical',
  name: 'Tropical Island',
  shortName: 'Tropical',
  emoji: '🌴',
  icon: uiIcons.tropical,
  background: tropicalArt.bg,
  tagline: 'Sunset beach harvest',
  cssVars: {
    '--bg': '#082f49',
    '--bg2': '#ea580c',
    '--text': '#fff7ed',
    '--muted': '#fed7aa',
    '--panel': 'rgba(12, 74, 110, 0.55)',
    '--panel-border': 'rgba(251, 146, 60, 0.35)',
    '--accent': '#f97316',
    '--accent-2': '#14b8a6',
    '--danger': '#fb7185',
    '--stage': 'linear-gradient(180deg, #7dd3fc 0%, #fb923c 42%, #ea580c 70%, #fde68a 100%)',
    '--hud': 'rgba(8, 47, 73, 0.72)',
    '--shadow': 'rgba(234, 88, 12, 0.28)',
    '--btn-text': '#082f49',
  },
  objects: buildObjects([
    {
      id: 'berry',
      name: 'Coconut berry',
      visual: {
        src: tropicalArt.berry,
        emoji: '🫐',
        fill: '#e11d48',
        stroke: '#9f1239',
        highlight: '#fda4af',
        style: 'tropical',
      },
    },
    {
      id: 'starfruit',
      name: 'Starfruit',
      visual: {
        src: tropicalArt.starfruit,
        emoji: '⭐',
        fill: '#facc15',
        stroke: '#a16207',
        highlight: '#fef08a',
        style: 'tropical',
      },
    },
    {
      id: 'kiwi',
      name: 'Kiwi',
      visual: {
        src: tropicalArt.kiwi,
        emoji: '🥝',
        fill: '#65a30d',
        stroke: '#3f6212',
        highlight: '#a3e635',
        style: 'tropical',
      },
    },
    {
      id: 'passion',
      name: 'Passion fruit',
      visual: {
        src: tropicalArt.passion,
        emoji: '🟣',
        fill: '#7c3aed',
        stroke: '#4c1d95',
        highlight: '#c4b5fd',
        style: 'tropical',
      },
    },
    {
      id: 'tropical-mango',
      name: 'Mango',
      visual: {
        src: tropicalArt.mango,
        emoji: '🥭',
        fill: '#fb923c',
        stroke: '#c2410c',
        highlight: '#fde68a',
        style: 'tropical',
        leaf: true,
      },
    },
    {
      id: 'banana',
      name: 'Banana',
      visual: {
        src: tropicalArt.banana,
        emoji: '🍌',
        fill: '#facc15',
        stroke: '#a16207',
        highlight: '#fef08a',
        style: 'tropical',
      },
    },
    {
      id: 'dragonfruit',
      name: 'Dragon fruit',
      visual: {
        src: tropicalArt.dragonfruit,
        emoji: '🐉',
        fill: '#db2777',
        stroke: '#9d174d',
        highlight: '#fda4af',
        style: 'tropical',
      },
    },
    {
      id: 'tropical-papaya',
      name: 'Papaya',
      visual: {
        src: tropicalArt.papaya,
        emoji: '🧡',
        fill: '#fb923c',
        stroke: '#c2410c',
        highlight: '#ffedd5',
        style: 'tropical',
      },
    },
    {
      id: 'tropical-coconut',
      name: 'Coconut',
      visual: {
        src: tropicalArt.coconut,
        emoji: '🥥',
        fill: '#78716c',
        stroke: '#44403c',
        highlight: '#e7e5e4',
        style: 'tropical',
      },
    },
    {
      id: 'tropical-pineapple',
      name: 'Pineapple',
      visual: {
        src: tropicalArt.pineapple,
        emoji: '🍍',
        fill: '#eab308',
        stroke: '#a16207',
        highlight: '#fef08a',
        style: 'tropical',
        leaf: true,
      },
    },
    {
      id: 'giant-melon',
      name: 'Watermelon',
      visual: {
        src: tropicalArt.watermelon,
        emoji: '🍉',
        fill: '#fb7185',
        stroke: '#166534',
        highlight: '#fecdd3',
        style: 'tropical',
      },
    },
  ]),
};
